// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build_trust_store`, `failure`, `failure`, `new`, `open_bytes_impl`, `success`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `try_from`

/// Opens untrusted bytes on FRB's asynchronous worker pool. No model or asset
/// data is returned unless the complete Rust verification pipeline succeeds.
Future<BridgeOpenResult> bundleOpenBytes({
  required List<int> bytes,
  required List<BridgeTrustKey> trustKeys,
  required BridgeVerificationPolicy policy,
  required BridgeLimits limits,
}) => RustLib.instance.api.crateApiBundleBundleOpenBytes(
  bytes: bytes,
  trustKeys: trustKeys,
  policy: policy,
  limits: limits,
);

/// Native convenience API. Flutter Web callers must use `bundle_open_bytes`.
Future<BridgeOpenResult> bundleOpenPath({
  required String path,
  required List<BridgeTrustKey> trustKeys,
  required BridgeVerificationPolicy policy,
  required BridgeLimits limits,
}) => RustLib.instance.api.crateApiBundleBundleOpenPath(
  path: path,
  trustKeys: trustKeys,
  policy: policy,
  limits: limits,
);

Future<BridgeAssetReadResult> bundleReadAsset({
  required BundleResource resource,
  required String logicalPath,
  required BigInt maximumBytes,
}) => RustLib.instance.api.crateApiBundleBundleReadAsset(
  resource: resource,
  logicalPath: logicalPath,
  maximumBytes: maximumBytes,
);

Future<BridgeDisposeResult> bundleDispose({required BundleResource resource}) =>
    RustLib.instance.api.crateApiBundleBundleDispose(resource: resource);

Future<BridgeLimits> bridgeHardLimits() =>
    RustLib.instance.api.crateApiBundleBridgeHardLimits();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeOpenedBundle>>
abstract class BridgeOpenedBundle implements RustOpaqueInterface {
  List<BridgeAssetDescriptor> get assets;

  Uint8List get compiledStory;

  BridgeManifest get manifest;

  BundleResource get resource;

  BridgeVerificationStatus get verification;

  set assets(List<BridgeAssetDescriptor> assets);

  set compiledStory(Uint8List compiledStory);

  set manifest(BridgeManifest manifest);

  set resource(BundleResource resource);

  set verification(BridgeVerificationStatus verification);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BundleResource>>
abstract class BundleResource implements RustOpaqueInterface {}

class BridgeAssetDescriptor {
  final String logicalPath;
  final BigInt size;
  final String sha256;

  const BridgeAssetDescriptor({
    required this.logicalPath,
    required this.size,
    required this.sha256,
  });

  @override
  int get hashCode => logicalPath.hashCode ^ size.hashCode ^ sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAssetDescriptor &&
          runtimeType == other.runtimeType &&
          logicalPath == other.logicalPath &&
          size == other.size &&
          sha256 == other.sha256;
}

class BridgeAssetReadResult {
  final Uint8List? bytes;
  final BridgeError? error;

  const BridgeAssetReadResult({this.bytes, this.error});

  @override
  int get hashCode => bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeAssetReadResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          error == other.error;
}

class BridgeDisposeResult {
  final bool released;
  final BridgeError? error;

  const BridgeDisposeResult({required this.released, this.error});

  @override
  int get hashCode => released.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeDisposeResult &&
          runtimeType == other.runtimeType &&
          released == other.released &&
          error == other.error;
}

class BridgeError {
  final String code;
  final String message;

  const BridgeError({required this.code, required this.message});

  @override
  int get hashCode => code.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          message == other.message;
}

class BridgeLimits {
  final BigInt maxArchiveBytes;
  final BigInt maxTotalUncompressedBytes;
  final BigInt maxEntryBytes;
  final BigInt maxCompiledIrBytes;
  final BigInt maxManifestBytes;
  final int maxEntries;
  final int maxPathBytes;
  final int maxSemanticDepth;

  const BridgeLimits({
    required this.maxArchiveBytes,
    required this.maxTotalUncompressedBytes,
    required this.maxEntryBytes,
    required this.maxCompiledIrBytes,
    required this.maxManifestBytes,
    required this.maxEntries,
    required this.maxPathBytes,
    required this.maxSemanticDepth,
  });

  @override
  int get hashCode =>
      maxArchiveBytes.hashCode ^
      maxTotalUncompressedBytes.hashCode ^
      maxEntryBytes.hashCode ^
      maxCompiledIrBytes.hashCode ^
      maxManifestBytes.hashCode ^
      maxEntries.hashCode ^
      maxPathBytes.hashCode ^
      maxSemanticDepth.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeLimits &&
          runtimeType == other.runtimeType &&
          maxArchiveBytes == other.maxArchiveBytes &&
          maxTotalUncompressedBytes == other.maxTotalUncompressedBytes &&
          maxEntryBytes == other.maxEntryBytes &&
          maxCompiledIrBytes == other.maxCompiledIrBytes &&
          maxManifestBytes == other.maxManifestBytes &&
          maxEntries == other.maxEntries &&
          maxPathBytes == other.maxPathBytes &&
          maxSemanticDepth == other.maxSemanticDepth;
}

class BridgeManifest {
  final int formatVersion;
  final String compilerVersion;
  final String schemaSha256;
  final BridgeProjectMetadata project;
  final String signerKeyId;
  final BridgeLimits resourceLimits;
  final List<BridgeManifestEntry> entries;

  const BridgeManifest({
    required this.formatVersion,
    required this.compilerVersion,
    required this.schemaSha256,
    required this.project,
    required this.signerKeyId,
    required this.resourceLimits,
    required this.entries,
  });

  @override
  int get hashCode =>
      formatVersion.hashCode ^
      compilerVersion.hashCode ^
      schemaSha256.hashCode ^
      project.hashCode ^
      signerKeyId.hashCode ^
      resourceLimits.hashCode ^
      entries.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeManifest &&
          runtimeType == other.runtimeType &&
          formatVersion == other.formatVersion &&
          compilerVersion == other.compilerVersion &&
          schemaSha256 == other.schemaSha256 &&
          project == other.project &&
          signerKeyId == other.signerKeyId &&
          resourceLimits == other.resourceLimits &&
          entries == other.entries;
}

class BridgeManifestEntry {
  final String path;
  final String entryType;
  final String compression;
  final BigInt compressedSize;
  final BigInt uncompressedSize;
  final String sha256;

  const BridgeManifestEntry({
    required this.path,
    required this.entryType,
    required this.compression,
    required this.compressedSize,
    required this.uncompressedSize,
    required this.sha256,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      entryType.hashCode ^
      compression.hashCode ^
      compressedSize.hashCode ^
      uncompressedSize.hashCode ^
      sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeManifestEntry &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          entryType == other.entryType &&
          compression == other.compression &&
          compressedSize == other.compressedSize &&
          uncompressedSize == other.uncompressedSize &&
          sha256 == other.sha256;
}

class BridgeOpenResult {
  final BridgeOpenedBundle? opened;
  final BridgeError? error;

  const BridgeOpenResult({this.opened, this.error});

  @override
  int get hashCode => opened.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeOpenResult &&
          runtimeType == other.runtimeType &&
          opened == other.opened &&
          error == other.error;
}

class BridgeProjectMetadata {
  final String id;
  final String name;
  final String version;

  const BridgeProjectMetadata({
    required this.id,
    required this.name,
    required this.version,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeProjectMetadata &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          version == other.version;
}

/// Host-provided Ed25519 trust material. The key must contain exactly 32 raw
/// public-key bytes. When present, `expected_key_id` must match its SHA-256 ID.
class BridgeTrustKey {
  final Uint8List publicKey;
  final String? expectedKeyId;

  const BridgeTrustKey({required this.publicKey, this.expectedKeyId});

  @override
  int get hashCode => publicKey.hashCode ^ expectedKeyId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeTrustKey &&
          runtimeType == other.runtimeType &&
          publicKey == other.publicKey &&
          expectedKeyId == other.expectedKeyId;
}

enum BridgeVerificationPolicy { strict, unsignedDevelopment }

class BridgeVerificationStatus {
  final String? signerKeyId;
  final bool isUnsignedDevelopment;

  const BridgeVerificationStatus({
    this.signerKeyId,
    required this.isUnsignedDevelopment,
  });

  @override
  int get hashCode => signerKeyId.hashCode ^ isUnsignedDevelopment.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeVerificationStatus &&
          runtimeType == other.runtimeType &&
          signerKeyId == other.signerKeyId &&
          isUnsignedDevelopment == other.isUnsignedDevelopment;
}
