// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'bundle.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `busy`, `delta_to_bridge`, `effect_to_bridge`, `event_to_bridge`, `failure`, `history_entry_to_bridge`, `history_to_bridge`, `lock_lease`, `open_bundle`, `simple`, `status_name`, `success`, `with_player`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `PlayerLease`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `try_from`

Future<BridgeRuntimeLimits> bundlePlayerHardLimits() =>
    RustLib.instance.api.crateApiPlayerBundlePlayerHardLimits();

Future<BridgeBundlePlayerOpenResult> bundlePlayerOpenFromBundle({
  required BundleResource bundle,
  required BridgeRuntimeLimits limits,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerOpenFromBundle(
  bundle: bundle,
  limits: limits,
);

Future<BridgeBundlePlayerOpenResult> bundlePlayerRestoreFromBundle({
  required BundleResource bundle,
  required List<int> save,
  required BridgeRuntimeLimits limits,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerRestoreFromBundle(
  bundle: bundle,
  save: save,
  limits: limits,
);

Future<BridgeBundlePlayerOpenResult> bundlePlayerOpenBytes({
  required List<int> bytes,
  required List<BridgeTrustKey> trustKeys,
  required BridgeVerificationPolicy policy,
  required BridgeLimits bundleLimits,
  required BridgeRuntimeLimits playerLimits,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerOpenBytes(
  bytes: bytes,
  trustKeys: trustKeys,
  policy: policy,
  bundleLimits: bundleLimits,
  playerLimits: playerLimits,
);

Future<BridgeBundlePlayerOpenResult> bundlePlayerRestoreBytes({
  required List<int> bytes,
  required List<int> save,
  required List<BridgeTrustKey> trustKeys,
  required BridgeVerificationPolicy policy,
  required BridgeLimits bundleLimits,
  required BridgeRuntimeLimits playerLimits,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerRestoreBytes(
  bytes: bytes,
  save: save,
  trustKeys: trustKeys,
  policy: policy,
  bundleLimits: bundleLimits,
  playerLimits: playerLimits,
);

Future<BridgeBundlePlayerOpenResult> bundlePlayerOpenPath({
  required String path,
  required List<BridgeTrustKey> trustKeys,
  required BridgeVerificationPolicy policy,
  required BridgeLimits bundleLimits,
  required BridgeRuntimeLimits playerLimits,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerOpenPath(
  path: path,
  trustKeys: trustKeys,
  policy: policy,
  bundleLimits: bundleLimits,
  playerLimits: playerLimits,
);

Future<BridgeBundlePlayerOpenResult> bundlePlayerRestorePath({
  required String path,
  required List<int> save,
  required List<BridgeTrustKey> trustKeys,
  required BridgeVerificationPolicy policy,
  required BridgeLimits bundleLimits,
  required BridgeRuntimeLimits playerLimits,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerRestorePath(
  path: path,
  save: save,
  trustKeys: trustKeys,
  policy: policy,
  bundleLimits: bundleLimits,
  playerLimits: playerLimits,
);

Future<BridgeBundlePlayerActionResult> bundlePlayerCurrent({
  required BundlePlayerResource resource,
}) =>
    RustLib.instance.api.crateApiPlayerBundlePlayerCurrent(resource: resource);

Future<BridgeBundlePlayerActionResult> bundlePlayerAdvance({
  required BundlePlayerResource resource,
}) =>
    RustLib.instance.api.crateApiPlayerBundlePlayerAdvance(resource: resource);

Future<BridgeBundlePlayerActionResult> bundlePlayerChoose({
  required BundlePlayerResource resource,
  required int index,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerChoose(
  resource: resource,
  index: index,
);

Future<BridgeBundlePlayerHistoryResult> bundlePlayerHistory({
  required BundlePlayerResource resource,
  required BigInt startSequence,
  required int maximum,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerHistory(
  resource: resource,
  startSequence: startSequence,
  maximum: maximum,
);

Future<BridgeBundlePlayerSaveResult> bundlePlayerExportSave({
  required BundlePlayerResource resource,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerExportSave(
  resource: resource,
);

Future<BridgeBundlePlayerAssetResult> bundlePlayerReadAsset({
  required BundlePlayerResource resource,
  required String logicalPath,
  required BigInt maximumBytes,
}) => RustLib.instance.api.crateApiPlayerBundlePlayerReadAsset(
  resource: resource,
  logicalPath: logicalPath,
  maximumBytes: maximumBytes,
);

Future<BridgeBundlePlayerDisposeResult> bundlePlayerDispose({
  required BundlePlayerResource resource,
}) =>
    RustLib.instance.api.crateApiPlayerBundlePlayerDispose(resource: resource);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeBundlePlayerOpened>>
abstract class BridgeBundlePlayerOpened implements RustOpaqueInterface {
  BridgePlayerDelta get current;

  BundlePlayerResource get resource;

  set current(BridgePlayerDelta current);

  set resource(BundlePlayerResource resource);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BundlePlayerResource>>
abstract class BundlePlayerResource implements RustOpaqueInterface {}

class BridgeBundlePlayerActionResult {
  final BridgePlayerDelta? delta;
  final BridgeRuntimeError? error;

  const BridgeBundlePlayerActionResult({this.delta, this.error});

  @override
  int get hashCode => delta.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBundlePlayerActionResult &&
          runtimeType == other.runtimeType &&
          delta == other.delta &&
          error == other.error;
}

class BridgeBundlePlayerAssetResult {
  final Uint8List? bytes;
  final BridgeRuntimeError? error;

  const BridgeBundlePlayerAssetResult({this.bytes, this.error});

  @override
  int get hashCode => bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBundlePlayerAssetResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          error == other.error;
}

class BridgeBundlePlayerDisposeResult {
  final bool released;
  final BridgeRuntimeError? error;

  const BridgeBundlePlayerDisposeResult({required this.released, this.error});

  @override
  int get hashCode => released.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBundlePlayerDisposeResult &&
          runtimeType == other.runtimeType &&
          released == other.released &&
          error == other.error;
}

class BridgeBundlePlayerHistoryResult {
  final BridgePlayerHistoryPage? page;
  final BridgeRuntimeError? error;

  const BridgeBundlePlayerHistoryResult({this.page, this.error});

  @override
  int get hashCode => page.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBundlePlayerHistoryResult &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          error == other.error;
}

class BridgeBundlePlayerOpenResult {
  final BridgeBundlePlayerOpened? opened;
  final BridgeRuntimeError? error;

  const BridgeBundlePlayerOpenResult({this.opened, this.error});

  @override
  int get hashCode => opened.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBundlePlayerOpenResult &&
          runtimeType == other.runtimeType &&
          opened == other.opened &&
          error == other.error;
}

class BridgeBundlePlayerSaveResult {
  final Uint8List? bytes;
  final BridgeRuntimeError? error;

  const BridgeBundlePlayerSaveResult({this.bytes, this.error});

  @override
  int get hashCode => bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeBundlePlayerSaveResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          error == other.error;
}

class BridgePlayerChoice {
  final String text;
  final String targetScene;

  const BridgePlayerChoice({required this.text, required this.targetScene});

  @override
  int get hashCode => text.hashCode ^ targetScene.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerChoice &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          targetScene == other.targetScene;
}

class BridgePlayerDelta {
  final BridgePlayerEvent event;
  final List<BridgePlayerEffect> effects;
  final String scene;
  final String status;
  final BigInt sequence;
  final BigInt firstRetainedSequence;
  final BigInt omittedHistoryCount;

  const BridgePlayerDelta({
    required this.event,
    required this.effects,
    required this.scene,
    required this.status,
    required this.sequence,
    required this.firstRetainedSequence,
    required this.omittedHistoryCount,
  });

  @override
  int get hashCode =>
      event.hashCode ^
      effects.hashCode ^
      scene.hashCode ^
      status.hashCode ^
      sequence.hashCode ^
      firstRetainedSequence.hashCode ^
      omittedHistoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerDelta &&
          runtimeType == other.runtimeType &&
          event == other.event &&
          effects == other.effects &&
          scene == other.scene &&
          status == other.status &&
          sequence == other.sequence &&
          firstRetainedSequence == other.firstRetainedSequence &&
          omittedHistoryCount == other.omittedHistoryCount;
}

class BridgePlayerEffect {
  final String kind;
  final String? path;

  const BridgePlayerEffect({required this.kind, this.path});

  @override
  int get hashCode => kind.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerEffect &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          path == other.path;
}

class BridgePlayerEvent {
  final String kind;
  final String? text;
  final String? scene;
  final String? actorId;
  final String? actorName;
  final String? emotion;
  final String? position;
  final String? portraitPath;
  final List<BridgePlayerChoice> choices;
  final BridgeRuntimeError? error;

  const BridgePlayerEvent({
    required this.kind,
    this.text,
    this.scene,
    this.actorId,
    this.actorName,
    this.emotion,
    this.position,
    this.portraitPath,
    required this.choices,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      scene.hashCode ^
      actorId.hashCode ^
      actorName.hashCode ^
      emotion.hashCode ^
      position.hashCode ^
      portraitPath.hashCode ^
      choices.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          scene == other.scene &&
          actorId == other.actorId &&
          actorName == other.actorName &&
          emotion == other.emotion &&
          position == other.position &&
          portraitPath == other.portraitPath &&
          choices == other.choices &&
          error == other.error;
}

class BridgePlayerHistoryEntry {
  final BigInt sequence;
  final BridgePlayerEvent event;
  final List<BridgePlayerEffect> effects;
  final String scene;

  const BridgePlayerHistoryEntry({
    required this.sequence,
    required this.event,
    required this.effects,
    required this.scene,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^ event.hashCode ^ effects.hashCode ^ scene.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerHistoryEntry &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          event == other.event &&
          effects == other.effects &&
          scene == other.scene;
}

class BridgePlayerHistoryPage {
  final List<BridgePlayerHistoryEntry> entries;
  final BigInt nextSequence;
  final BigInt firstRetainedSequence;
  final BigInt omittedHistoryCount;

  const BridgePlayerHistoryPage({
    required this.entries,
    required this.nextSequence,
    required this.firstRetainedSequence,
    required this.omittedHistoryCount,
  });

  @override
  int get hashCode =>
      entries.hashCode ^
      nextSequence.hashCode ^
      firstRetainedSequence.hashCode ^
      omittedHistoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerHistoryPage &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          nextSequence == other.nextSequence &&
          firstRetainedSequence == other.firstRetainedSequence &&
          omittedHistoryCount == other.omittedHistoryCount;
}

class BridgeRuntimeError {
  final String code;
  final String scene;
  final String message;
  final String? resource;
  final BigInt? actual;
  final BigInt? limit;

  const BridgeRuntimeError({
    required this.code,
    required this.scene,
    required this.message,
    this.resource,
    this.actual,
    this.limit,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      scene.hashCode ^
      message.hashCode ^
      resource.hashCode ^
      actual.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRuntimeError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          scene == other.scene &&
          message == other.message &&
          resource == other.resource &&
          actual == other.actual &&
          limit == other.limit;
}

class BridgeRuntimeLimits {
  final BigInt operationsPerInteraction;
  final BigInt logicDepth;
  final BigInt pendingEventsPerScene;
  final BigInt arrayElements;
  final BigInt renderedBytes;
  final BigInt historyEntries;
  final BigInt historyBytes;
  final BigInt saveBytes;

  const BridgeRuntimeLimits({
    required this.operationsPerInteraction,
    required this.logicDepth,
    required this.pendingEventsPerScene,
    required this.arrayElements,
    required this.renderedBytes,
    required this.historyEntries,
    required this.historyBytes,
    required this.saveBytes,
  });

  @override
  int get hashCode =>
      operationsPerInteraction.hashCode ^
      logicDepth.hashCode ^
      pendingEventsPerScene.hashCode ^
      arrayElements.hashCode ^
      renderedBytes.hashCode ^
      historyEntries.hashCode ^
      historyBytes.hashCode ^
      saveBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeRuntimeLimits &&
          runtimeType == other.runtimeType &&
          operationsPerInteraction == other.operationsPerInteraction &&
          logicDepth == other.logicDepth &&
          pendingEventsPerScene == other.pendingEventsPerScene &&
          arrayElements == other.arrayElements &&
          renderedBytes == other.renderedBytes &&
          historyEntries == other.historyEntries &&
          historyBytes == other.historyBytes &&
          saveBytes == other.saveBytes;
}
