// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `delta_to_bridge`, `effect_to_bridge`, `event_to_bridge`, `failure`, `history_entry_to_bridge`, `history_page_to_bridge`, `lock_player`, `simple`, `status_name`, `success`, `with_player`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `try_from`

Future<BridgePlayerLimits> sourcePlayerHardLimits() =>
    RustLib.instance.api.crateApiPlayerV2SourcePlayerHardLimits();

Future<BridgeSourcePlayerOpenResult> sourcePlayerOpenRaw({
  required String source,
  required BridgePlayerLimits limits,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerOpenRaw(
  source: source,
  limits: limits,
);

Future<BridgeSourcePlayerOpenResult> sourcePlayerOpenPath({
  required String path,
  required BridgePlayerLimits limits,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerOpenPath(
  path: path,
  limits: limits,
);

Future<BridgeSourcePlayerOpenResult> sourcePlayerRestoreRaw({
  required String source,
  required List<int> save,
  required BridgePlayerLimits limits,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerRestoreRaw(
  source: source,
  save: save,
  limits: limits,
);

Future<BridgeSourcePlayerOpenResult> sourcePlayerRestorePath({
  required String path,
  required List<int> save,
  required BridgePlayerLimits limits,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerRestorePath(
  path: path,
  save: save,
  limits: limits,
);

Future<BridgePlayerActionResult> sourcePlayerCurrent({
  required SourcePlayerResource resource,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerCurrent(
  resource: resource,
);

Future<BridgePlayerActionResult> sourcePlayerAdvance({
  required SourcePlayerResource resource,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerAdvance(
  resource: resource,
);

Future<BridgePlayerActionResult> sourcePlayerChoose({
  required SourcePlayerResource resource,
  required int index,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerChoose(
  resource: resource,
  index: index,
);

Future<BridgePlayerHistoryResult> sourcePlayerHistory({
  required SourcePlayerResource resource,
  required BigInt startSequence,
  required int maximum,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerHistory(
  resource: resource,
  startSequence: startSequence,
  maximum: maximum,
);

Future<BridgePlayerSaveResult> sourcePlayerExportSave({
  required SourcePlayerResource resource,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerExportSave(
  resource: resource,
);

Future<BridgePlayerDisposeResult> sourcePlayerDispose({
  required SourcePlayerResource resource,
}) => RustLib.instance.api.crateApiPlayerV2SourcePlayerDispose(
  resource: resource,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BridgeSourcePlayerOpened>>
abstract class BridgeSourcePlayerOpened implements RustOpaqueInterface {
  BridgePlayerDelta get current;

  SourcePlayerResource get resource;

  set current(BridgePlayerDelta current);

  set resource(SourcePlayerResource resource);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<SourcePlayerResource>>
abstract class SourcePlayerResource implements RustOpaqueInterface {}

class BridgeHistoryEntry {
  final BigInt sequence;
  final BridgeSemanticEvent event;
  final List<BridgeMediaEffect> effects;
  final String scene;

  const BridgeHistoryEntry({
    required this.sequence,
    required this.event,
    required this.effects,
    required this.scene,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^ event.hashCode ^ effects.hashCode ^ scene.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryEntry &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          event == other.event &&
          effects == other.effects &&
          scene == other.scene;
}

class BridgeHistoryPage {
  final List<BridgeHistoryEntry> entries;
  final BigInt nextSequence;
  final BigInt firstRetainedSequence;
  final BigInt omittedHistoryCount;

  const BridgeHistoryPage({
    required this.entries,
    required this.nextSequence,
    required this.firstRetainedSequence,
    required this.omittedHistoryCount,
  });

  @override
  int get hashCode =>
      entries.hashCode ^
      nextSequence.hashCode ^
      firstRetainedSequence.hashCode ^
      omittedHistoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeHistoryPage &&
          runtimeType == other.runtimeType &&
          entries == other.entries &&
          nextSequence == other.nextSequence &&
          firstRetainedSequence == other.firstRetainedSequence &&
          omittedHistoryCount == other.omittedHistoryCount;
}

class BridgeMediaEffect {
  final String kind;
  final String? path;

  const BridgeMediaEffect({required this.kind, this.path});

  @override
  int get hashCode => kind.hashCode ^ path.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeMediaEffect &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          path == other.path;
}

class BridgePlayerActionResult {
  final BridgePlayerDelta? delta;
  final BridgePlayerError? error;

  const BridgePlayerActionResult({this.delta, this.error});

  @override
  int get hashCode => delta.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerActionResult &&
          runtimeType == other.runtimeType &&
          delta == other.delta &&
          error == other.error;
}

class BridgePlayerDelta {
  final BridgeSemanticEvent event;
  final List<BridgeMediaEffect> effects;
  final String scene;
  final String status;
  final BigInt sequence;
  final BigInt firstRetainedSequence;
  final BigInt omittedHistoryCount;

  const BridgePlayerDelta({
    required this.event,
    required this.effects,
    required this.scene,
    required this.status,
    required this.sequence,
    required this.firstRetainedSequence,
    required this.omittedHistoryCount,
  });

  @override
  int get hashCode =>
      event.hashCode ^
      effects.hashCode ^
      scene.hashCode ^
      status.hashCode ^
      sequence.hashCode ^
      firstRetainedSequence.hashCode ^
      omittedHistoryCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerDelta &&
          runtimeType == other.runtimeType &&
          event == other.event &&
          effects == other.effects &&
          scene == other.scene &&
          status == other.status &&
          sequence == other.sequence &&
          firstRetainedSequence == other.firstRetainedSequence &&
          omittedHistoryCount == other.omittedHistoryCount;
}

class BridgePlayerDisposeResult {
  final bool released;
  final BridgePlayerError? error;

  const BridgePlayerDisposeResult({required this.released, this.error});

  @override
  int get hashCode => released.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerDisposeResult &&
          runtimeType == other.runtimeType &&
          released == other.released &&
          error == other.error;
}

class BridgePlayerError {
  final String code;
  final String scene;
  final String message;
  final String? resource;
  final BigInt? actual;
  final BigInt? limit;

  const BridgePlayerError({
    required this.code,
    required this.scene,
    required this.message,
    this.resource,
    this.actual,
    this.limit,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      scene.hashCode ^
      message.hashCode ^
      resource.hashCode ^
      actual.hashCode ^
      limit.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerError &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          scene == other.scene &&
          message == other.message &&
          resource == other.resource &&
          actual == other.actual &&
          limit == other.limit;
}

class BridgePlayerHistoryResult {
  final BridgeHistoryPage? page;
  final BridgePlayerError? error;

  const BridgePlayerHistoryResult({this.page, this.error});

  @override
  int get hashCode => page.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerHistoryResult &&
          runtimeType == other.runtimeType &&
          page == other.page &&
          error == other.error;
}

class BridgePlayerLimits {
  final BigInt operationsPerInteraction;
  final BigInt logicDepth;
  final BigInt pendingEventsPerScene;
  final BigInt arrayElements;
  final BigInt renderedBytes;
  final BigInt historyEntries;
  final BigInt historyBytes;
  final BigInt saveBytes;

  const BridgePlayerLimits({
    required this.operationsPerInteraction,
    required this.logicDepth,
    required this.pendingEventsPerScene,
    required this.arrayElements,
    required this.renderedBytes,
    required this.historyEntries,
    required this.historyBytes,
    required this.saveBytes,
  });

  @override
  int get hashCode =>
      operationsPerInteraction.hashCode ^
      logicDepth.hashCode ^
      pendingEventsPerScene.hashCode ^
      arrayElements.hashCode ^
      renderedBytes.hashCode ^
      historyEntries.hashCode ^
      historyBytes.hashCode ^
      saveBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerLimits &&
          runtimeType == other.runtimeType &&
          operationsPerInteraction == other.operationsPerInteraction &&
          logicDepth == other.logicDepth &&
          pendingEventsPerScene == other.pendingEventsPerScene &&
          arrayElements == other.arrayElements &&
          renderedBytes == other.renderedBytes &&
          historyEntries == other.historyEntries &&
          historyBytes == other.historyBytes &&
          saveBytes == other.saveBytes;
}

class BridgePlayerSaveResult {
  final Uint8List? bytes;
  final BridgePlayerError? error;

  const BridgePlayerSaveResult({this.bytes, this.error});

  @override
  int get hashCode => bytes.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgePlayerSaveResult &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          error == other.error;
}

class BridgeSemanticChoice {
  final String text;
  final String targetScene;

  const BridgeSemanticChoice({required this.text, required this.targetScene});

  @override
  int get hashCode => text.hashCode ^ targetScene.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSemanticChoice &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          targetScene == other.targetScene;
}

class BridgeSemanticEvent {
  final String kind;
  final String? text;
  final String? scene;
  final String? actorId;
  final String? actorName;
  final String? emotion;
  final String? position;
  final String? portraitPath;
  final List<BridgeSemanticChoice> choices;
  final BridgePlayerError? error;

  const BridgeSemanticEvent({
    required this.kind,
    this.text,
    this.scene,
    this.actorId,
    this.actorName,
    this.emotion,
    this.position,
    this.portraitPath,
    required this.choices,
    this.error,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      text.hashCode ^
      scene.hashCode ^
      actorId.hashCode ^
      actorName.hashCode ^
      emotion.hashCode ^
      position.hashCode ^
      portraitPath.hashCode ^
      choices.hashCode ^
      error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSemanticEvent &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          text == other.text &&
          scene == other.scene &&
          actorId == other.actorId &&
          actorName == other.actorName &&
          emotion == other.emotion &&
          position == other.position &&
          portraitPath == other.portraitPath &&
          choices == other.choices &&
          error == other.error;
}

class BridgeSourcePlayerOpenResult {
  final BridgeSourcePlayerOpened? opened;
  final BridgePlayerError? error;

  const BridgeSourcePlayerOpenResult({this.opened, this.error});

  @override
  int get hashCode => opened.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BridgeSourcePlayerOpenResult &&
          runtimeType == other.runtimeType &&
          opened == other.opened &&
          error == other.error;
}
