// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/bundle.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1496165417;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'storyscript_bundle',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  List<BridgeAssetDescriptor>
  crateApiBundleBridgeOpenedBundleAutoAccessorGetAssets({
    required BridgeOpenedBundle that,
  });

  Uint8List crateApiBundleBridgeOpenedBundleAutoAccessorGetCompiledStory({
    required BridgeOpenedBundle that,
  });

  BridgeManifest crateApiBundleBridgeOpenedBundleAutoAccessorGetManifest({
    required BridgeOpenedBundle that,
  });

  BundleResource crateApiBundleBridgeOpenedBundleAutoAccessorGetResource({
    required BridgeOpenedBundle that,
  });

  BridgeVerificationStatus
  crateApiBundleBridgeOpenedBundleAutoAccessorGetVerification({
    required BridgeOpenedBundle that,
  });

  void crateApiBundleBridgeOpenedBundleAutoAccessorSetAssets({
    required BridgeOpenedBundle that,
    required List<BridgeAssetDescriptor> assets,
  });

  void crateApiBundleBridgeOpenedBundleAutoAccessorSetCompiledStory({
    required BridgeOpenedBundle that,
    required Uint8List compiledStory,
  });

  void crateApiBundleBridgeOpenedBundleAutoAccessorSetManifest({
    required BridgeOpenedBundle that,
    required BridgeManifest manifest,
  });

  void crateApiBundleBridgeOpenedBundleAutoAccessorSetResource({
    required BridgeOpenedBundle that,
    required BundleResource resource,
  });

  void crateApiBundleBridgeOpenedBundleAutoAccessorSetVerification({
    required BridgeOpenedBundle that,
    required BridgeVerificationStatus verification,
  });

  Future<BridgeLimits> crateApiBundleBridgeHardLimits();

  Future<BridgeDisposeResult> crateApiBundleBundleDispose({
    required BundleResource resource,
  });

  Future<BridgeOpenResult> crateApiBundleBundleOpenBytes({
    required List<int> bytes,
    required List<BridgeTrustKey> trustKeys,
    required BridgeVerificationPolicy policy,
    required BridgeLimits limits,
  });

  Future<BridgeOpenResult> crateApiBundleBundleOpenPath({
    required String path,
    required List<BridgeTrustKey> trustKeys,
    required BridgeVerificationPolicy policy,
    required BridgeLimits limits,
  });

  Future<BridgeAssetReadResult> crateApiBundleBundleReadAsset({
    required BundleResource resource,
    required String logicalPath,
    required BigInt maximumBytes,
  });

  Future<void> crateApiInitInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BridgeOpenedBundle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BridgeOpenedBundle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeOpenedBundlePtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BundleResource;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BundleResource;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BundleResourcePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<BridgeAssetDescriptor>
  crateApiBundleBridgeOpenedBundleAutoAccessorGetAssets({
    required BridgeOpenedBundle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_bridge_asset_descriptor,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorGetAssetsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorGetAssetsConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_get_assets",
        argNames: ["that"],
      );

  @override
  Uint8List crateApiBundleBridgeOpenedBundleAutoAccessorGetCompiledStory({
    required BridgeOpenedBundle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorGetCompiledStoryConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorGetCompiledStoryConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_get_compiled_story",
        argNames: ["that"],
      );

  @override
  BridgeManifest crateApiBundleBridgeOpenedBundleAutoAccessorGetManifest({
    required BridgeOpenedBundle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_manifest,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorGetManifestConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorGetManifestConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_get_manifest",
        argNames: ["that"],
      );

  @override
  BundleResource crateApiBundleBridgeOpenedBundleAutoAccessorGetResource({
    required BridgeOpenedBundle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorGetResourceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorGetResourceConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_get_resource",
        argNames: ["that"],
      );

  @override
  BridgeVerificationStatus
  crateApiBundleBridgeOpenedBundleAutoAccessorGetVerification({
    required BridgeOpenedBundle that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_verification_status,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorGetVerificationConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorGetVerificationConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_get_verification",
        argNames: ["that"],
      );

  @override
  void crateApiBundleBridgeOpenedBundleAutoAccessorSetAssets({
    required BridgeOpenedBundle that,
    required List<BridgeAssetDescriptor> assets,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          sse_encode_list_bridge_asset_descriptor(assets, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorSetAssetsConstMeta,
        argValues: [that, assets],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorSetAssetsConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_set_assets",
        argNames: ["that", "assets"],
      );

  @override
  void crateApiBundleBridgeOpenedBundleAutoAccessorSetCompiledStory({
    required BridgeOpenedBundle that,
    required Uint8List compiledStory,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          sse_encode_list_prim_u_8_strict(compiledStory, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorSetCompiledStoryConstMeta,
        argValues: [that, compiledStory],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorSetCompiledStoryConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_set_compiled_story",
        argNames: ["that", "compiledStory"],
      );

  @override
  void crateApiBundleBridgeOpenedBundleAutoAccessorSetManifest({
    required BridgeOpenedBundle that,
    required BridgeManifest manifest,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          sse_encode_bridge_manifest(manifest, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorSetManifestConstMeta,
        argValues: [that, manifest],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorSetManifestConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_set_manifest",
        argNames: ["that", "manifest"],
      );

  @override
  void crateApiBundleBridgeOpenedBundleAutoAccessorSetResource({
    required BridgeOpenedBundle that,
    required BundleResource resource,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
            resource,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorSetResourceConstMeta,
        argValues: [that, resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorSetResourceConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_set_resource",
        argNames: ["that", "resource"],
      );

  @override
  void crateApiBundleBridgeOpenedBundleAutoAccessorSetVerification({
    required BridgeOpenedBundle that,
    required BridgeVerificationStatus verification,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            that,
            serializer,
          );
          sse_encode_bridge_verification_status(verification, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiBundleBridgeOpenedBundleAutoAccessorSetVerificationConstMeta,
        argValues: [that, verification],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiBundleBridgeOpenedBundleAutoAccessorSetVerificationConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeOpenedBundle_auto_accessor_set_verification",
        argNames: ["that", "verification"],
      );

  @override
  Future<BridgeLimits> crateApiBundleBridgeHardLimits() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_limits,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBundleBridgeHardLimitsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBundleBridgeHardLimitsConstMeta =>
      const TaskConstMeta(debugName: "bridge_hard_limits", argNames: []);

  @override
  Future<BridgeDisposeResult> crateApiBundleBundleDispose({
    required BundleResource resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
            resource,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_dispose_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBundleBundleDisposeConstMeta,
        argValues: [resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBundleBundleDisposeConstMeta =>
      const TaskConstMeta(debugName: "bundle_dispose", argNames: ["resource"]);

  @override
  Future<BridgeOpenResult> crateApiBundleBundleOpenBytes({
    required List<int> bytes,
    required List<BridgeTrustKey> trustKeys,
    required BridgeVerificationPolicy policy,
    required BridgeLimits limits,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(bytes, serializer);
          sse_encode_list_bridge_trust_key(trustKeys, serializer);
          sse_encode_bridge_verification_policy(policy, serializer);
          sse_encode_box_autoadd_bridge_limits(limits, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_open_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBundleBundleOpenBytesConstMeta,
        argValues: [bytes, trustKeys, policy, limits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBundleBundleOpenBytesConstMeta =>
      const TaskConstMeta(
        debugName: "bundle_open_bytes",
        argNames: ["bytes", "trustKeys", "policy", "limits"],
      );

  @override
  Future<BridgeOpenResult> crateApiBundleBundleOpenPath({
    required String path,
    required List<BridgeTrustKey> trustKeys,
    required BridgeVerificationPolicy policy,
    required BridgeLimits limits,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_bridge_trust_key(trustKeys, serializer);
          sse_encode_bridge_verification_policy(policy, serializer);
          sse_encode_box_autoadd_bridge_limits(limits, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_open_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBundleBundleOpenPathConstMeta,
        argValues: [path, trustKeys, policy, limits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBundleBundleOpenPathConstMeta =>
      const TaskConstMeta(
        debugName: "bundle_open_path",
        argNames: ["path", "trustKeys", "policy", "limits"],
      );

  @override
  Future<BridgeAssetReadResult> crateApiBundleBundleReadAsset({
    required BundleResource resource,
    required String logicalPath,
    required BigInt maximumBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
            resource,
            serializer,
          );
          sse_encode_String(logicalPath, serializer);
          sse_encode_u_64(maximumBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_asset_read_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBundleBundleReadAssetConstMeta,
        argValues: [resource, logicalPath, maximumBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBundleBundleReadAssetConstMeta =>
      const TaskConstMeta(
        debugName: "bundle_read_asset",
        argNames: ["resource", "logicalPath", "maximumBytes"],
      );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BridgeOpenedBundle => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BridgeOpenedBundle => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BundleResource => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BundleResource => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource;

  @protected
  BridgeOpenedBundle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BundleResource
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BundleResourceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeOpenedBundle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeOpenedBundle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BundleResource
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BundleResourceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeOpenedBundle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BundleResource
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BundleResourceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeOpenedBundle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
      raw,
    );
  }

  @protected
  BridgeError dco_decode_box_autoadd_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_error(raw);
  }

  @protected
  BridgeLimits dco_decode_box_autoadd_bridge_limits(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_limits(raw);
  }

  @protected
  BridgeAssetDescriptor dco_decode_bridge_asset_descriptor(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeAssetDescriptor(
      logicalPath: dco_decode_String(arr[0]),
      size: dco_decode_u_64(arr[1]),
      sha256: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeAssetReadResult dco_decode_bridge_asset_read_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeAssetReadResult(
      bytes: dco_decode_opt_list_prim_u_8_strict(arr[0]),
      error: dco_decode_opt_box_autoadd_bridge_error(arr[1]),
    );
  }

  @protected
  BridgeDisposeResult dco_decode_bridge_dispose_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeDisposeResult(
      released: dco_decode_bool(arr[0]),
      error: dco_decode_opt_box_autoadd_bridge_error(arr[1]),
    );
  }

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeError(
      code: dco_decode_String(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  BridgeLimits dco_decode_bridge_limits(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BridgeLimits(
      maxArchiveBytes: dco_decode_u_64(arr[0]),
      maxTotalUncompressedBytes: dco_decode_u_64(arr[1]),
      maxEntryBytes: dco_decode_u_64(arr[2]),
      maxCompiledIrBytes: dco_decode_u_64(arr[3]),
      maxManifestBytes: dco_decode_u_64(arr[4]),
      maxEntries: dco_decode_u_32(arr[5]),
      maxPathBytes: dco_decode_u_32(arr[6]),
      maxSemanticDepth: dco_decode_u_32(arr[7]),
    );
  }

  @protected
  BridgeManifest dco_decode_bridge_manifest(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeManifest(
      formatVersion: dco_decode_u_32(arr[0]),
      compilerVersion: dco_decode_String(arr[1]),
      schemaSha256: dco_decode_String(arr[2]),
      project: dco_decode_bridge_project_metadata(arr[3]),
      signerKeyId: dco_decode_String(arr[4]),
      resourceLimits: dco_decode_bridge_limits(arr[5]),
      entries: dco_decode_list_bridge_manifest_entry(arr[6]),
    );
  }

  @protected
  BridgeManifestEntry dco_decode_bridge_manifest_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgeManifestEntry(
      path: dco_decode_String(arr[0]),
      entryType: dco_decode_String(arr[1]),
      compression: dco_decode_String(arr[2]),
      compressedSize: dco_decode_u_64(arr[3]),
      uncompressedSize: dco_decode_u_64(arr[4]),
      sha256: dco_decode_String(arr[5]),
    );
  }

  @protected
  BridgeOpenResult dco_decode_bridge_open_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeOpenResult(
      opened:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            arr[0],
          ),
      error: dco_decode_opt_box_autoadd_bridge_error(arr[1]),
    );
  }

  @protected
  BridgeProjectMetadata dco_decode_bridge_project_metadata(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return BridgeProjectMetadata(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      version: dco_decode_String(arr[2]),
    );
  }

  @protected
  BridgeTrustKey dco_decode_bridge_trust_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeTrustKey(
      publicKey: dco_decode_list_prim_u_8_strict(arr[0]),
      expectedKeyId: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  BridgeVerificationPolicy dco_decode_bridge_verification_policy(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeVerificationPolicy.values[raw as int];
  }

  @protected
  BridgeVerificationStatus dco_decode_bridge_verification_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeVerificationStatus(
      signerKeyId: dco_decode_opt_String(arr[0]),
      isUnsignedDevelopment: dco_decode_bool(arr[1]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<BridgeAssetDescriptor> dco_decode_list_bridge_asset_descriptor(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_asset_descriptor)
        .toList();
  }

  @protected
  List<BridgeManifestEntry> dco_decode_list_bridge_manifest_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_manifest_entry)
        .toList();
  }

  @protected
  List<BridgeTrustKey> dco_decode_list_bridge_trust_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_trust_key).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BridgeOpenedBundle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
            raw,
          );
  }

  @protected
  BridgeError? dco_decode_opt_box_autoadd_bridge_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_error(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  BridgeOpenedBundle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BundleResource
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BundleResourceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BridgeOpenedBundle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BridgeOpenedBundle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BundleResource
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BundleResourceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BridgeOpenedBundle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeOpenedBundleImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BundleResource
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BundleResourceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeOpenedBundle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
      deserializer,
    ));
  }

  @protected
  BridgeError sse_decode_box_autoadd_bridge_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_error(deserializer));
  }

  @protected
  BridgeLimits sse_decode_box_autoadd_bridge_limits(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_limits(deserializer));
  }

  @protected
  BridgeAssetDescriptor sse_decode_bridge_asset_descriptor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_logicalPath = sse_decode_String(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    return BridgeAssetDescriptor(
      logicalPath: var_logicalPath,
      size: var_size,
      sha256: var_sha256,
    );
  }

  @protected
  BridgeAssetReadResult sse_decode_bridge_asset_read_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_error = sse_decode_opt_box_autoadd_bridge_error(deserializer);
    return BridgeAssetReadResult(bytes: var_bytes, error: var_error);
  }

  @protected
  BridgeDisposeResult sse_decode_bridge_dispose_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_released = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_box_autoadd_bridge_error(deserializer);
    return BridgeDisposeResult(released: var_released, error: var_error);
  }

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    return BridgeError(code: var_code, message: var_message);
  }

  @protected
  BridgeLimits sse_decode_bridge_limits(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_maxArchiveBytes = sse_decode_u_64(deserializer);
    var var_maxTotalUncompressedBytes = sse_decode_u_64(deserializer);
    var var_maxEntryBytes = sse_decode_u_64(deserializer);
    var var_maxCompiledIrBytes = sse_decode_u_64(deserializer);
    var var_maxManifestBytes = sse_decode_u_64(deserializer);
    var var_maxEntries = sse_decode_u_32(deserializer);
    var var_maxPathBytes = sse_decode_u_32(deserializer);
    var var_maxSemanticDepth = sse_decode_u_32(deserializer);
    return BridgeLimits(
      maxArchiveBytes: var_maxArchiveBytes,
      maxTotalUncompressedBytes: var_maxTotalUncompressedBytes,
      maxEntryBytes: var_maxEntryBytes,
      maxCompiledIrBytes: var_maxCompiledIrBytes,
      maxManifestBytes: var_maxManifestBytes,
      maxEntries: var_maxEntries,
      maxPathBytes: var_maxPathBytes,
      maxSemanticDepth: var_maxSemanticDepth,
    );
  }

  @protected
  BridgeManifest sse_decode_bridge_manifest(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_formatVersion = sse_decode_u_32(deserializer);
    var var_compilerVersion = sse_decode_String(deserializer);
    var var_schemaSha256 = sse_decode_String(deserializer);
    var var_project = sse_decode_bridge_project_metadata(deserializer);
    var var_signerKeyId = sse_decode_String(deserializer);
    var var_resourceLimits = sse_decode_bridge_limits(deserializer);
    var var_entries = sse_decode_list_bridge_manifest_entry(deserializer);
    return BridgeManifest(
      formatVersion: var_formatVersion,
      compilerVersion: var_compilerVersion,
      schemaSha256: var_schemaSha256,
      project: var_project,
      signerKeyId: var_signerKeyId,
      resourceLimits: var_resourceLimits,
      entries: var_entries,
    );
  }

  @protected
  BridgeManifestEntry sse_decode_bridge_manifest_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_path = sse_decode_String(deserializer);
    var var_entryType = sse_decode_String(deserializer);
    var var_compression = sse_decode_String(deserializer);
    var var_compressedSize = sse_decode_u_64(deserializer);
    var var_uncompressedSize = sse_decode_u_64(deserializer);
    var var_sha256 = sse_decode_String(deserializer);
    return BridgeManifestEntry(
      path: var_path,
      entryType: var_entryType,
      compression: var_compression,
      compressedSize: var_compressedSize,
      uncompressedSize: var_uncompressedSize,
      sha256: var_sha256,
    );
  }

  @protected
  BridgeOpenResult sse_decode_bridge_open_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_opened =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
          deserializer,
        );
    var var_error = sse_decode_opt_box_autoadd_bridge_error(deserializer);
    return BridgeOpenResult(opened: var_opened, error: var_error);
  }

  @protected
  BridgeProjectMetadata sse_decode_bridge_project_metadata(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    return BridgeProjectMetadata(
      id: var_id,
      name: var_name,
      version: var_version,
    );
  }

  @protected
  BridgeTrustKey sse_decode_bridge_trust_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_publicKey = sse_decode_list_prim_u_8_strict(deserializer);
    var var_expectedKeyId = sse_decode_opt_String(deserializer);
    return BridgeTrustKey(
      publicKey: var_publicKey,
      expectedKeyId: var_expectedKeyId,
    );
  }

  @protected
  BridgeVerificationPolicy sse_decode_bridge_verification_policy(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return BridgeVerificationPolicy.values[inner];
  }

  @protected
  BridgeVerificationStatus sse_decode_bridge_verification_status(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_signerKeyId = sse_decode_opt_String(deserializer);
    var var_isUnsignedDevelopment = sse_decode_bool(deserializer);
    return BridgeVerificationStatus(
      signerKeyId: var_signerKeyId,
      isUnsignedDevelopment: var_isUnsignedDevelopment,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<BridgeAssetDescriptor> sse_decode_list_bridge_asset_descriptor(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeAssetDescriptor>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_asset_descriptor(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeManifestEntry> sse_decode_list_bridge_manifest_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeManifestEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_manifest_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeTrustKey> sse_decode_list_bridge_trust_key(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeTrustKey>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_trust_key(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeOpenedBundle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  BridgeError? sse_decode_opt_box_autoadd_bridge_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeOpenedBundleImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    BundleResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BundleResourceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeOpenedBundleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeOpenedBundleImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    BundleResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BundleResourceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeOpenedBundleImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    BundleResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BundleResourceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_bridge_error(
    BridgeError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_limits(
    BridgeLimits self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_limits(self, serializer);
  }

  @protected
  void sse_encode_bridge_asset_descriptor(
    BridgeAssetDescriptor self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.logicalPath, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_bridge_asset_read_result(
    BridgeAssetReadResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_opt_box_autoadd_bridge_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_dispose_result(
    BridgeDisposeResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.released, serializer);
    sse_encode_opt_box_autoadd_bridge_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_bridge_limits(BridgeLimits self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.maxArchiveBytes, serializer);
    sse_encode_u_64(self.maxTotalUncompressedBytes, serializer);
    sse_encode_u_64(self.maxEntryBytes, serializer);
    sse_encode_u_64(self.maxCompiledIrBytes, serializer);
    sse_encode_u_64(self.maxManifestBytes, serializer);
    sse_encode_u_32(self.maxEntries, serializer);
    sse_encode_u_32(self.maxPathBytes, serializer);
    sse_encode_u_32(self.maxSemanticDepth, serializer);
  }

  @protected
  void sse_encode_bridge_manifest(
    BridgeManifest self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.formatVersion, serializer);
    sse_encode_String(self.compilerVersion, serializer);
    sse_encode_String(self.schemaSha256, serializer);
    sse_encode_bridge_project_metadata(self.project, serializer);
    sse_encode_String(self.signerKeyId, serializer);
    sse_encode_bridge_limits(self.resourceLimits, serializer);
    sse_encode_list_bridge_manifest_entry(self.entries, serializer);
  }

  @protected
  void sse_encode_bridge_manifest_entry(
    BridgeManifestEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.entryType, serializer);
    sse_encode_String(self.compression, serializer);
    sse_encode_u_64(self.compressedSize, serializer);
    sse_encode_u_64(self.uncompressedSize, serializer);
    sse_encode_String(self.sha256, serializer);
  }

  @protected
  void sse_encode_bridge_open_result(
    BridgeOpenResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
      self.opened,
      serializer,
    );
    sse_encode_opt_box_autoadd_bridge_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_project_metadata(
    BridgeProjectMetadata self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
  }

  @protected
  void sse_encode_bridge_trust_key(
    BridgeTrustKey self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.publicKey, serializer);
    sse_encode_opt_String(self.expectedKeyId, serializer);
  }

  @protected
  void sse_encode_bridge_verification_policy(
    BridgeVerificationPolicy self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_bridge_verification_status(
    BridgeVerificationStatus self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.signerKeyId, serializer);
    sse_encode_bool(self.isUnsignedDevelopment, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_bridge_asset_descriptor(
    List<BridgeAssetDescriptor> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_asset_descriptor(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_manifest_entry(
    List<BridgeManifestEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_manifest_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_trust_key(
    List<BridgeTrustKey> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_trust_key(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_error(
    BridgeError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class BridgeOpenedBundleImpl extends RustOpaque implements BridgeOpenedBundle {
  // Not to be used by end users
  BridgeOpenedBundleImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BridgeOpenedBundleImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BridgeOpenedBundle,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BridgeOpenedBundle,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_BridgeOpenedBundlePtr,
  );

  List<BridgeAssetDescriptor> get assets => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorGetAssets(that: this);

  Uint8List get compiledStory => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorGetCompiledStory(that: this);

  BridgeManifest get manifest => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorGetManifest(that: this);

  BundleResource get resource => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorGetResource(that: this);

  BridgeVerificationStatus get verification => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorGetVerification(that: this);

  set assets(List<BridgeAssetDescriptor> assets) => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorSetAssets(
        that: this,
        assets: assets,
      );

  set compiledStory(Uint8List compiledStory) => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorSetCompiledStory(
        that: this,
        compiledStory: compiledStory,
      );

  set manifest(BridgeManifest manifest) => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorSetManifest(
        that: this,
        manifest: manifest,
      );

  set resource(BundleResource resource) => RustLib.instance.api
      .crateApiBundleBridgeOpenedBundleAutoAccessorSetResource(
        that: this,
        resource: resource,
      );

  set verification(BridgeVerificationStatus verification) => RustLib
      .instance
      .api
      .crateApiBundleBridgeOpenedBundleAutoAccessorSetVerification(
        that: this,
        verification: verification,
      );
}

@sealed
class BundleResourceImpl extends RustOpaque implements BundleResource {
  // Not to be used by end users
  BundleResourceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BundleResourceImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_BundleResource,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_BundleResource,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_BundleResourcePtr,
  );
}
