// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/bundle.dart';
import 'api/player.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeBundlePlayerOpenedPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeOpenedBundlePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BundlePlayerResourcePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BundleResourcePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource;

  @protected
  BridgeBundlePlayerOpened
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeOpenedBundle
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  );

  @protected
  BundlePlayerResource
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    dynamic raw,
  );

  @protected
  BundleResource
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    dynamic raw,
  );

  @protected
  BridgeBundlePlayerOpened
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeOpenedBundle
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  );

  @protected
  BridgeBundlePlayerOpened
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeOpenedBundle
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  );

  @protected
  BundlePlayerResource
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    dynamic raw,
  );

  @protected
  BundleResource
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    dynamic raw,
  );

  @protected
  BridgeBundlePlayerOpened
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeOpenedBundle
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  );

  @protected
  BundlePlayerResource
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    dynamic raw,
  );

  @protected
  BundleResource
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeBundlePlayerOpened
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeOpenedBundle
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  );

  @protected
  BridgeError dco_decode_box_autoadd_bridge_error(dynamic raw);

  @protected
  BridgeLimits dco_decode_box_autoadd_bridge_limits(dynamic raw);

  @protected
  BridgePlayerDelta dco_decode_box_autoadd_bridge_player_delta(dynamic raw);

  @protected
  BridgePlayerHistoryPage dco_decode_box_autoadd_bridge_player_history_page(
    dynamic raw,
  );

  @protected
  BridgeRuntimeError dco_decode_box_autoadd_bridge_runtime_error(dynamic raw);

  @protected
  BridgeRuntimeLimits dco_decode_box_autoadd_bridge_runtime_limits(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BridgeAssetDescriptor dco_decode_bridge_asset_descriptor(dynamic raw);

  @protected
  BridgeAssetReadResult dco_decode_bridge_asset_read_result(dynamic raw);

  @protected
  BridgeBundlePlayerActionResult dco_decode_bridge_bundle_player_action_result(
    dynamic raw,
  );

  @protected
  BridgeBundlePlayerAssetResult dco_decode_bridge_bundle_player_asset_result(
    dynamic raw,
  );

  @protected
  BridgeBundlePlayerDisposeResult
  dco_decode_bridge_bundle_player_dispose_result(dynamic raw);

  @protected
  BridgeBundlePlayerHistoryResult
  dco_decode_bridge_bundle_player_history_result(dynamic raw);

  @protected
  BridgeBundlePlayerOpenResult dco_decode_bridge_bundle_player_open_result(
    dynamic raw,
  );

  @protected
  BridgeBundlePlayerSaveResult dco_decode_bridge_bundle_player_save_result(
    dynamic raw,
  );

  @protected
  BridgeDisposeResult dco_decode_bridge_dispose_result(dynamic raw);

  @protected
  BridgeError dco_decode_bridge_error(dynamic raw);

  @protected
  BridgeLimits dco_decode_bridge_limits(dynamic raw);

  @protected
  BridgeManifest dco_decode_bridge_manifest(dynamic raw);

  @protected
  BridgeManifestEntry dco_decode_bridge_manifest_entry(dynamic raw);

  @protected
  BridgeOpenResult dco_decode_bridge_open_result(dynamic raw);

  @protected
  BridgePlayerChoice dco_decode_bridge_player_choice(dynamic raw);

  @protected
  BridgePlayerDelta dco_decode_bridge_player_delta(dynamic raw);

  @protected
  BridgePlayerEffect dco_decode_bridge_player_effect(dynamic raw);

  @protected
  BridgePlayerEvent dco_decode_bridge_player_event(dynamic raw);

  @protected
  BridgePlayerHistoryEntry dco_decode_bridge_player_history_entry(dynamic raw);

  @protected
  BridgePlayerHistoryPage dco_decode_bridge_player_history_page(dynamic raw);

  @protected
  BridgeProjectMetadata dco_decode_bridge_project_metadata(dynamic raw);

  @protected
  BridgeRuntimeError dco_decode_bridge_runtime_error(dynamic raw);

  @protected
  BridgeRuntimeLimits dco_decode_bridge_runtime_limits(dynamic raw);

  @protected
  BridgeTrustKey dco_decode_bridge_trust_key(dynamic raw);

  @protected
  BridgeVerificationPolicy dco_decode_bridge_verification_policy(dynamic raw);

  @protected
  BridgeVerificationStatus dco_decode_bridge_verification_status(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<BridgeAssetDescriptor> dco_decode_list_bridge_asset_descriptor(
    dynamic raw,
  );

  @protected
  List<BridgeManifestEntry> dco_decode_list_bridge_manifest_entry(dynamic raw);

  @protected
  List<BridgePlayerChoice> dco_decode_list_bridge_player_choice(dynamic raw);

  @protected
  List<BridgePlayerEffect> dco_decode_list_bridge_player_effect(dynamic raw);

  @protected
  List<BridgePlayerHistoryEntry> dco_decode_list_bridge_player_history_entry(
    dynamic raw,
  );

  @protected
  List<BridgeTrustKey> dco_decode_list_bridge_trust_key(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BridgeBundlePlayerOpened?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeOpenedBundle?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    dynamic raw,
  );

  @protected
  BridgeError? dco_decode_opt_box_autoadd_bridge_error(dynamic raw);

  @protected
  BridgePlayerDelta? dco_decode_opt_box_autoadd_bridge_player_delta(
    dynamic raw,
  );

  @protected
  BridgePlayerHistoryPage?
  dco_decode_opt_box_autoadd_bridge_player_history_page(dynamic raw);

  @protected
  BridgeRuntimeError? dco_decode_opt_box_autoadd_bridge_runtime_error(
    dynamic raw,
  );

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  BridgeBundlePlayerOpened
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenedBundle
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  );

  @protected
  BundlePlayerResource
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    SseDeserializer deserializer,
  );

  @protected
  BundleResource
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerOpened
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenedBundle
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerOpened
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenedBundle
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  );

  @protected
  BundlePlayerResource
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    SseDeserializer deserializer,
  );

  @protected
  BundleResource
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerOpened
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenedBundle
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  );

  @protected
  BundlePlayerResource
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    SseDeserializer deserializer,
  );

  @protected
  BundleResource
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeBundlePlayerOpened
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenedBundle
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_box_autoadd_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeLimits sse_decode_box_autoadd_bridge_limits(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDelta sse_decode_box_autoadd_bridge_player_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerHistoryPage sse_decode_box_autoadd_bridge_player_history_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeError sse_decode_box_autoadd_bridge_runtime_error(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeLimits sse_decode_box_autoadd_bridge_runtime_limits(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BridgeAssetDescriptor sse_decode_bridge_asset_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  BridgeAssetReadResult sse_decode_bridge_asset_read_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerActionResult sse_decode_bridge_bundle_player_action_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerAssetResult sse_decode_bridge_bundle_player_asset_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerDisposeResult
  sse_decode_bridge_bundle_player_dispose_result(SseDeserializer deserializer);

  @protected
  BridgeBundlePlayerHistoryResult
  sse_decode_bridge_bundle_player_history_result(SseDeserializer deserializer);

  @protected
  BridgeBundlePlayerOpenResult sse_decode_bridge_bundle_player_open_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeBundlePlayerSaveResult sse_decode_bridge_bundle_player_save_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeDisposeResult sse_decode_bridge_dispose_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError sse_decode_bridge_error(SseDeserializer deserializer);

  @protected
  BridgeLimits sse_decode_bridge_limits(SseDeserializer deserializer);

  @protected
  BridgeManifest sse_decode_bridge_manifest(SseDeserializer deserializer);

  @protected
  BridgeManifestEntry sse_decode_bridge_manifest_entry(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenResult sse_decode_bridge_open_result(SseDeserializer deserializer);

  @protected
  BridgePlayerChoice sse_decode_bridge_player_choice(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDelta sse_decode_bridge_player_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerEffect sse_decode_bridge_player_effect(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerEvent sse_decode_bridge_player_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerHistoryEntry sse_decode_bridge_player_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerHistoryPage sse_decode_bridge_player_history_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgeProjectMetadata sse_decode_bridge_project_metadata(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeError sse_decode_bridge_runtime_error(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeLimits sse_decode_bridge_runtime_limits(
    SseDeserializer deserializer,
  );

  @protected
  BridgeTrustKey sse_decode_bridge_trust_key(SseDeserializer deserializer);

  @protected
  BridgeVerificationPolicy sse_decode_bridge_verification_policy(
    SseDeserializer deserializer,
  );

  @protected
  BridgeVerificationStatus sse_decode_bridge_verification_status(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<BridgeAssetDescriptor> sse_decode_list_bridge_asset_descriptor(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeManifestEntry> sse_decode_list_bridge_manifest_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgePlayerChoice> sse_decode_list_bridge_player_choice(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgePlayerEffect> sse_decode_list_bridge_player_effect(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgePlayerHistoryEntry> sse_decode_list_bridge_player_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeTrustKey> sse_decode_list_bridge_trust_key(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BridgeBundlePlayerOpened?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeOpenedBundle?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    SseDeserializer deserializer,
  );

  @protected
  BridgeError? sse_decode_opt_box_autoadd_bridge_error(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDelta? sse_decode_opt_box_autoadd_bridge_player_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerHistoryPage?
  sse_decode_opt_box_autoadd_bridge_player_history_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgeRuntimeError? sse_decode_opt_box_autoadd_bridge_runtime_error(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    BridgeBundlePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    BundlePlayerResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    BundleResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    BridgeBundlePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    BridgeBundlePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    BundlePlayerResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    BundleResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    BridgeBundlePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    BundlePlayerResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    BundleResource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    BridgeBundlePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_error(
    BridgeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_limits(
    BridgeLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_player_delta(
    BridgePlayerDelta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_player_history_page(
    BridgePlayerHistoryPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_runtime_error(
    BridgeRuntimeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_runtime_limits(
    BridgeRuntimeLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_asset_descriptor(
    BridgeAssetDescriptor self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_asset_read_result(
    BridgeAssetReadResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_bundle_player_action_result(
    BridgeBundlePlayerActionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_bundle_player_asset_result(
    BridgeBundlePlayerAssetResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_bundle_player_dispose_result(
    BridgeBundlePlayerDisposeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_bundle_player_history_result(
    BridgeBundlePlayerHistoryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_bundle_player_open_result(
    BridgeBundlePlayerOpenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_bundle_player_save_result(
    BridgeBundlePlayerSaveResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_dispose_result(
    BridgeDisposeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_error(BridgeError self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_limits(BridgeLimits self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_manifest(
    BridgeManifest self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_manifest_entry(
    BridgeManifestEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_open_result(
    BridgeOpenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_choice(
    BridgePlayerChoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_delta(
    BridgePlayerDelta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_effect(
    BridgePlayerEffect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_event(
    BridgePlayerEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_history_entry(
    BridgePlayerHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_history_page(
    BridgePlayerHistoryPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_project_metadata(
    BridgeProjectMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_runtime_error(
    BridgeRuntimeError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_runtime_limits(
    BridgeRuntimeLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_trust_key(
    BridgeTrustKey self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_verification_policy(
    BridgeVerificationPolicy self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_verification_status(
    BridgeVerificationStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_bridge_asset_descriptor(
    List<BridgeAssetDescriptor> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_manifest_entry(
    List<BridgeManifestEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_player_choice(
    List<BridgePlayerChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_player_effect(
    List<BridgePlayerEffect> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_player_history_entry(
    List<BridgePlayerHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_trust_key(
    List<BridgeTrustKey> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    BridgeBundlePlayerOpened? self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    BridgeOpenedBundle? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_error(
    BridgeError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_player_delta(
    BridgePlayerDelta? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_player_history_page(
    BridgePlayerHistoryPage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_runtime_error(
    BridgeRuntimeError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeBundlePlayerOpened(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeOpenedBundle(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundlePlayerResource(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBundleResource(
    int ptr,
  );
}
