// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';
import 'api/player_v2.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 714466409;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'storyscript_player_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  BridgePlayerDelta
  crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetCurrent({
    required BridgeSourcePlayerOpened that,
  });

  SourcePlayerResource
  crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetResource({
    required BridgeSourcePlayerOpened that,
  });

  void crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetCurrent({
    required BridgeSourcePlayerOpened that,
    required BridgePlayerDelta current,
  });

  void crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetResource({
    required BridgeSourcePlayerOpened that,
    required SourcePlayerResource resource,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  BridgeState crateApiPlayerPlayerAdvance({required BigInt sessionId});

  BridgeState crateApiPlayerPlayerChoose({
    required BigInt sessionId,
    required int index,
  });

  bool crateApiPlayerPlayerClose({required BigInt sessionId});

  BridgeState crateApiPlayerPlayerGetState({required BigInt sessionId});

  BigInt crateApiPlayerPlayerOpen({required String path});

  BigInt crateApiPlayerPlayerOpenRaw({required String source});

  Future<BridgePlayerActionResult> crateApiPlayerV2SourcePlayerAdvance({
    required SourcePlayerResource resource,
  });

  Future<BridgePlayerActionResult> crateApiPlayerV2SourcePlayerChoose({
    required SourcePlayerResource resource,
    required int index,
  });

  Future<BridgePlayerActionResult> crateApiPlayerV2SourcePlayerCurrent({
    required SourcePlayerResource resource,
  });

  Future<BridgePlayerDisposeResult> crateApiPlayerV2SourcePlayerDispose({
    required SourcePlayerResource resource,
  });

  Future<BridgePlayerSaveResult> crateApiPlayerV2SourcePlayerExportSave({
    required SourcePlayerResource resource,
  });

  Future<BridgePlayerLimits> crateApiPlayerV2SourcePlayerHardLimits();

  Future<BridgePlayerHistoryResult> crateApiPlayerV2SourcePlayerHistory({
    required SourcePlayerResource resource,
    required BigInt startSequence,
    required int maximum,
  });

  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerOpenPath({
    required String path,
    required BridgePlayerLimits limits,
  });

  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerOpenRaw({
    required String source,
    required BridgePlayerLimits limits,
  });

  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerRestorePath({
    required String path,
    required List<int> save,
    required BridgePlayerLimits limits,
  });

  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerRestoreRaw({
    required String source,
    required List<int> save,
    required BridgePlayerLimits limits,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BridgeSourcePlayerOpened;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BridgeSourcePlayerOpened;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeSourcePlayerOpenedPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SourcePlayerResource;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SourcePlayerResource;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SourcePlayerResourcePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  BridgePlayerDelta
  crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetCurrent({
    required BridgeSourcePlayerOpened that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_delta,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetCurrentConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetCurrentConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeSourcePlayerOpened_auto_accessor_get_current",
        argNames: ["that"],
      );

  @override
  SourcePlayerResource
  crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetResource({
    required BridgeSourcePlayerOpened that,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetResourceConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetResourceConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeSourcePlayerOpened_auto_accessor_get_resource",
        argNames: ["that"],
      );

  @override
  void crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetCurrent({
    required BridgeSourcePlayerOpened that,
    required BridgePlayerDelta current,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
            that,
            serializer,
          );
          sse_encode_bridge_player_delta(current, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetCurrentConstMeta,
        argValues: [that, current],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetCurrentConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeSourcePlayerOpened_auto_accessor_set_current",
        argNames: ["that", "current"],
      );

  @override
  void crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetResource({
    required BridgeSourcePlayerOpened that,
    required SourcePlayerResource resource,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
            that,
            serializer,
          );
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetResourceConstMeta,
        argValues: [that, resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetResourceConstMeta =>
      const TaskConstMeta(
        debugName: "BridgeSourcePlayerOpened_auto_accessor_set_resource",
        argNames: ["that", "resource"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  BridgeState crateApiPlayerPlayerAdvance({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerAdvanceConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerAdvanceConstMeta =>
      const TaskConstMeta(debugName: "player_advance", argNames: ["sessionId"]);

  @override
  BridgeState crateApiPlayerPlayerChoose({
    required BigInt sessionId,
    required int index,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          sse_encode_u_32(index, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerChooseConstMeta,
        argValues: [sessionId, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerChooseConstMeta => const TaskConstMeta(
    debugName: "player_choose",
    argNames: ["sessionId", "index"],
  );

  @override
  bool crateApiPlayerPlayerClose({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerPlayerCloseConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerCloseConstMeta =>
      const TaskConstMeta(debugName: "player_close", argNames: ["sessionId"]);

  @override
  BridgeState crateApiPlayerPlayerGetState({required BigInt sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_state,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerGetStateConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerGetStateConstMeta =>
      const TaskConstMeta(
        debugName: "player_get_state",
        argNames: ["sessionId"],
      );

  @override
  BigInt crateApiPlayerPlayerOpen({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerOpenConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerOpenConstMeta =>
      const TaskConstMeta(debugName: "player_open", argNames: ["path"]);

  @override
  BigInt crateApiPlayerPlayerOpenRaw({required String source}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiPlayerPlayerOpenRawConstMeta,
        argValues: [source],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerPlayerOpenRawConstMeta =>
      const TaskConstMeta(debugName: "player_open_raw", argNames: ["source"]);

  @override
  Future<BridgePlayerActionResult> crateApiPlayerV2SourcePlayerAdvance({
    required SourcePlayerResource resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerAdvanceConstMeta,
        argValues: [resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerAdvanceConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_advance",
        argNames: ["resource"],
      );

  @override
  Future<BridgePlayerActionResult> crateApiPlayerV2SourcePlayerChoose({
    required SourcePlayerResource resource,
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          sse_encode_u_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerChooseConstMeta,
        argValues: [resource, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerChooseConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_choose",
        argNames: ["resource", "index"],
      );

  @override
  Future<BridgePlayerActionResult> crateApiPlayerV2SourcePlayerCurrent({
    required SourcePlayerResource resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_action_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerCurrentConstMeta,
        argValues: [resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerCurrentConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_current",
        argNames: ["resource"],
      );

  @override
  Future<BridgePlayerDisposeResult> crateApiPlayerV2SourcePlayerDispose({
    required SourcePlayerResource resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_dispose_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerDisposeConstMeta,
        argValues: [resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerDisposeConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_dispose",
        argNames: ["resource"],
      );

  @override
  Future<BridgePlayerSaveResult> crateApiPlayerV2SourcePlayerExportSave({
    required SourcePlayerResource resource,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_save_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerExportSaveConstMeta,
        argValues: [resource],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerExportSaveConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_export_save",
        argNames: ["resource"],
      );

  @override
  Future<BridgePlayerLimits> crateApiPlayerV2SourcePlayerHardLimits() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_limits,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerHardLimitsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerHardLimitsConstMeta =>
      const TaskConstMeta(debugName: "source_player_hard_limits", argNames: []);

  @override
  Future<BridgePlayerHistoryResult> crateApiPlayerV2SourcePlayerHistory({
    required SourcePlayerResource resource,
    required BigInt startSequence,
    required int maximum,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
            resource,
            serializer,
          );
          sse_encode_u_64(startSequence, serializer);
          sse_encode_u_32(maximum, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_player_history_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerHistoryConstMeta,
        argValues: [resource, startSequence, maximum],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_history",
        argNames: ["resource", "startSequence", "maximum"],
      );

  @override
  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerOpenPath({
    required String path,
    required BridgePlayerLimits limits,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_box_autoadd_bridge_player_limits(limits, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_source_player_open_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerOpenPathConstMeta,
        argValues: [path, limits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerOpenPathConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_open_path",
        argNames: ["path", "limits"],
      );

  @override
  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerOpenRaw({
    required String source,
    required BridgePlayerLimits limits,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_box_autoadd_bridge_player_limits(limits, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_source_player_open_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerOpenRawConstMeta,
        argValues: [source, limits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerOpenRawConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_open_raw",
        argNames: ["source", "limits"],
      );

  @override
  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerRestorePath({
    required String path,
    required List<int> save,
    required BridgePlayerLimits limits,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_list_prim_u_8_loose(save, serializer);
          sse_encode_box_autoadd_bridge_player_limits(limits, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_source_player_open_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerRestorePathConstMeta,
        argValues: [path, save, limits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerRestorePathConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_restore_path",
        argNames: ["path", "save", "limits"],
      );

  @override
  Future<BridgeSourcePlayerOpenResult> crateApiPlayerV2SourcePlayerRestoreRaw({
    required String source,
    required List<int> save,
    required BridgePlayerLimits limits,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(source, serializer);
          sse_encode_list_prim_u_8_loose(save, serializer);
          sse_encode_box_autoadd_bridge_player_limits(limits, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bridge_source_player_open_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPlayerV2SourcePlayerRestoreRawConstMeta,
        argValues: [source, save, limits],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPlayerV2SourcePlayerRestoreRawConstMeta =>
      const TaskConstMeta(
        debugName: "source_player_restore_raw",
        argNames: ["source", "save", "limits"],
      );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_BridgeSourcePlayerOpened => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_BridgeSourcePlayerOpened => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_SourcePlayerResource => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_SourcePlayerResource => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource;

  @protected
  BridgeSourcePlayerOpened
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  SourcePlayerResource
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SourcePlayerResourceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeSourcePlayerOpened
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  BridgeSourcePlayerOpened
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  SourcePlayerResource
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SourcePlayerResourceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  BridgeSourcePlayerOpened
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalDcoDecode(
      raw as List<dynamic>,
    );
  }

  @protected
  SourcePlayerResource
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SourcePlayerResourceImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BridgeSourcePlayerOpened
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
      raw,
    );
  }

  @protected
  BridgeHistoryPage dco_decode_box_autoadd_bridge_history_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_history_page(raw);
  }

  @protected
  BridgePlayerDelta dco_decode_box_autoadd_bridge_player_delta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_player_delta(raw);
  }

  @protected
  BridgePlayerError dco_decode_box_autoadd_bridge_player_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_player_error(raw);
  }

  @protected
  BridgePlayerLimits dco_decode_box_autoadd_bridge_player_limits(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_player_limits(raw);
  }

  @protected
  BridgeStep dco_decode_box_autoadd_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_bridge_step(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  BridgeChoice dco_decode_bridge_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeChoice(
      text: dco_decode_String(arr[0]),
      target: dco_decode_String(arr[1]),
    );
  }

  @protected
  BridgeHistoryEntry dco_decode_bridge_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeHistoryEntry(
      sequence: dco_decode_u_64(arr[0]),
      event: dco_decode_bridge_semantic_event(arr[1]),
      effects: dco_decode_list_bridge_media_effect(arr[2]),
      scene: dco_decode_String(arr[3]),
    );
  }

  @protected
  BridgeHistoryPage dco_decode_bridge_history_page(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return BridgeHistoryPage(
      entries: dco_decode_list_bridge_history_entry(arr[0]),
      nextSequence: dco_decode_u_64(arr[1]),
      firstRetainedSequence: dco_decode_u_64(arr[2]),
      omittedHistoryCount: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  BridgeMediaEffect dco_decode_bridge_media_effect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeMediaEffect(
      kind: dco_decode_String(arr[0]),
      path: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  BridgePlayerActionResult dco_decode_bridge_player_action_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgePlayerActionResult(
      delta: dco_decode_opt_box_autoadd_bridge_player_delta(arr[0]),
      error: dco_decode_opt_box_autoadd_bridge_player_error(arr[1]),
    );
  }

  @protected
  BridgePlayerDelta dco_decode_bridge_player_delta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgePlayerDelta(
      event: dco_decode_bridge_semantic_event(arr[0]),
      effects: dco_decode_list_bridge_media_effect(arr[1]),
      scene: dco_decode_String(arr[2]),
      status: dco_decode_String(arr[3]),
      sequence: dco_decode_u_64(arr[4]),
      firstRetainedSequence: dco_decode_u_64(arr[5]),
      omittedHistoryCount: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  BridgePlayerDisposeResult dco_decode_bridge_player_dispose_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgePlayerDisposeResult(
      released: dco_decode_bool(arr[0]),
      error: dco_decode_opt_box_autoadd_bridge_player_error(arr[1]),
    );
  }

  @protected
  BridgePlayerError dco_decode_bridge_player_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return BridgePlayerError(
      code: dco_decode_String(arr[0]),
      scene: dco_decode_String(arr[1]),
      message: dco_decode_String(arr[2]),
      resource: dco_decode_opt_String(arr[3]),
      actual: dco_decode_opt_box_autoadd_u_64(arr[4]),
      limit: dco_decode_opt_box_autoadd_u_64(arr[5]),
    );
  }

  @protected
  BridgePlayerHistoryResult dco_decode_bridge_player_history_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgePlayerHistoryResult(
      page: dco_decode_opt_box_autoadd_bridge_history_page(arr[0]),
      error: dco_decode_opt_box_autoadd_bridge_player_error(arr[1]),
    );
  }

  @protected
  BridgePlayerLimits dco_decode_bridge_player_limits(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return BridgePlayerLimits(
      operationsPerInteraction: dco_decode_u_64(arr[0]),
      logicDepth: dco_decode_u_64(arr[1]),
      pendingEventsPerScene: dco_decode_u_64(arr[2]),
      arrayElements: dco_decode_u_64(arr[3]),
      renderedBytes: dco_decode_u_64(arr[4]),
      historyEntries: dco_decode_u_64(arr[5]),
      historyBytes: dco_decode_u_64(arr[6]),
      saveBytes: dco_decode_u_64(arr[7]),
    );
  }

  @protected
  BridgePlayerSaveResult dco_decode_bridge_player_save_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgePlayerSaveResult(
      bytes: dco_decode_opt_list_prim_u_8_strict(arr[0]),
      error: dco_decode_opt_box_autoadd_bridge_player_error(arr[1]),
    );
  }

  @protected
  BridgeSemanticChoice dco_decode_bridge_semantic_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeSemanticChoice(
      text: dco_decode_String(arr[0]),
      targetScene: dco_decode_String(arr[1]),
    );
  }

  @protected
  BridgeSemanticEvent dco_decode_bridge_semantic_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return BridgeSemanticEvent(
      kind: dco_decode_String(arr[0]),
      text: dco_decode_opt_String(arr[1]),
      scene: dco_decode_opt_String(arr[2]),
      actorId: dco_decode_opt_String(arr[3]),
      actorName: dco_decode_opt_String(arr[4]),
      emotion: dco_decode_opt_String(arr[5]),
      position: dco_decode_opt_String(arr[6]),
      portraitPath: dco_decode_opt_String(arr[7]),
      choices: dco_decode_list_bridge_semantic_choice(arr[8]),
      error: dco_decode_opt_box_autoadd_bridge_player_error(arr[9]),
    );
  }

  @protected
  BridgeSourcePlayerOpenResult dco_decode_bridge_source_player_open_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeSourcePlayerOpenResult(
      opened:
          dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
            arr[0],
          ),
      error: dco_decode_opt_box_autoadd_bridge_player_error(arr[1]),
    );
  }

  @protected
  BridgeState dco_decode_bridge_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return BridgeState(
      sessionId: dco_decode_u_64(arr[0]),
      scriptName: dco_decode_String(arr[1]),
      scene: dco_decode_String(arr[2]),
      bg: dco_decode_opt_String(arr[3]),
      bgm: dco_decode_opt_String(arr[4]),
      finished: dco_decode_bool(arr[5]),
      variables: dco_decode_list_bridge_variable(arr[6]),
      current: dco_decode_opt_box_autoadd_bridge_step(arr[7]),
      history: dco_decode_list_bridge_step(arr[8]),
    );
  }

  @protected
  BridgeStep dco_decode_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return BridgeStep(
      kind: dco_decode_String(arr[0]),
      text: dco_decode_opt_String(arr[1]),
      actorName: dco_decode_opt_String(arr[2]),
      actorId: dco_decode_opt_String(arr[3]),
      emotion: dco_decode_opt_String(arr[4]),
      position: dco_decode_opt_String(arr[5]),
      choices: dco_decode_list_bridge_choice(arr[6]),
    );
  }

  @protected
  BridgeVariable dco_decode_bridge_variable(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return BridgeVariable(
      name: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  List<BridgeChoice> dco_decode_list_bridge_choice(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_choice).toList();
  }

  @protected
  List<BridgeHistoryEntry> dco_decode_list_bridge_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_history_entry).toList();
  }

  @protected
  List<BridgeMediaEffect> dco_decode_list_bridge_media_effect(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_media_effect).toList();
  }

  @protected
  List<BridgeSemanticChoice> dco_decode_list_bridge_semantic_choice(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_bridge_semantic_choice)
        .toList();
  }

  @protected
  List<BridgeStep> dco_decode_list_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_step).toList();
  }

  @protected
  List<BridgeVariable> dco_decode_list_bridge_variable(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_bridge_variable).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BridgeSourcePlayerOpened?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
            raw,
          );
  }

  @protected
  BridgeHistoryPage? dco_decode_opt_box_autoadd_bridge_history_page(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_history_page(raw);
  }

  @protected
  BridgePlayerDelta? dco_decode_opt_box_autoadd_bridge_player_delta(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_player_delta(raw);
  }

  @protected
  BridgePlayerError? dco_decode_opt_box_autoadd_bridge_player_error(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_player_error(raw);
  }

  @protected
  BridgeStep? dco_decode_opt_box_autoadd_bridge_step(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_bridge_step(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  BridgeSourcePlayerOpened
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SourcePlayerResource
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SourcePlayerResourceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BridgeSourcePlayerOpened
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BridgeSourcePlayerOpened
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SourcePlayerResource
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SourcePlayerResourceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  BridgeSourcePlayerOpened
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return BridgeSourcePlayerOpenedImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  SourcePlayerResource
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return SourcePlayerResourceImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BridgeSourcePlayerOpened
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
      deserializer,
    ));
  }

  @protected
  BridgeHistoryPage sse_decode_box_autoadd_bridge_history_page(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_history_page(deserializer));
  }

  @protected
  BridgePlayerDelta sse_decode_box_autoadd_bridge_player_delta(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_player_delta(deserializer));
  }

  @protected
  BridgePlayerError sse_decode_box_autoadd_bridge_player_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_player_error(deserializer));
  }

  @protected
  BridgePlayerLimits sse_decode_box_autoadd_bridge_player_limits(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_player_limits(deserializer));
  }

  @protected
  BridgeStep sse_decode_box_autoadd_bridge_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_bridge_step(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  BridgeChoice sse_decode_bridge_choice(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_target = sse_decode_String(deserializer);
    return BridgeChoice(text: var_text, target: var_target);
  }

  @protected
  BridgeHistoryEntry sse_decode_bridge_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sequence = sse_decode_u_64(deserializer);
    var var_event = sse_decode_bridge_semantic_event(deserializer);
    var var_effects = sse_decode_list_bridge_media_effect(deserializer);
    var var_scene = sse_decode_String(deserializer);
    return BridgeHistoryEntry(
      sequence: var_sequence,
      event: var_event,
      effects: var_effects,
      scene: var_scene,
    );
  }

  @protected
  BridgeHistoryPage sse_decode_bridge_history_page(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_entries = sse_decode_list_bridge_history_entry(deserializer);
    var var_nextSequence = sse_decode_u_64(deserializer);
    var var_firstRetainedSequence = sse_decode_u_64(deserializer);
    var var_omittedHistoryCount = sse_decode_u_64(deserializer);
    return BridgeHistoryPage(
      entries: var_entries,
      nextSequence: var_nextSequence,
      firstRetainedSequence: var_firstRetainedSequence,
      omittedHistoryCount: var_omittedHistoryCount,
    );
  }

  @protected
  BridgeMediaEffect sse_decode_bridge_media_effect(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_path = sse_decode_opt_String(deserializer);
    return BridgeMediaEffect(kind: var_kind, path: var_path);
  }

  @protected
  BridgePlayerActionResult sse_decode_bridge_player_action_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_delta = sse_decode_opt_box_autoadd_bridge_player_delta(
      deserializer,
    );
    var var_error = sse_decode_opt_box_autoadd_bridge_player_error(
      deserializer,
    );
    return BridgePlayerActionResult(delta: var_delta, error: var_error);
  }

  @protected
  BridgePlayerDelta sse_decode_bridge_player_delta(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_event = sse_decode_bridge_semantic_event(deserializer);
    var var_effects = sse_decode_list_bridge_media_effect(deserializer);
    var var_scene = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_sequence = sse_decode_u_64(deserializer);
    var var_firstRetainedSequence = sse_decode_u_64(deserializer);
    var var_omittedHistoryCount = sse_decode_u_64(deserializer);
    return BridgePlayerDelta(
      event: var_event,
      effects: var_effects,
      scene: var_scene,
      status: var_status,
      sequence: var_sequence,
      firstRetainedSequence: var_firstRetainedSequence,
      omittedHistoryCount: var_omittedHistoryCount,
    );
  }

  @protected
  BridgePlayerDisposeResult sse_decode_bridge_player_dispose_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_released = sse_decode_bool(deserializer);
    var var_error = sse_decode_opt_box_autoadd_bridge_player_error(
      deserializer,
    );
    return BridgePlayerDisposeResult(released: var_released, error: var_error);
  }

  @protected
  BridgePlayerError sse_decode_bridge_player_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_scene = sse_decode_String(deserializer);
    var var_message = sse_decode_String(deserializer);
    var var_resource = sse_decode_opt_String(deserializer);
    var var_actual = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_limit = sse_decode_opt_box_autoadd_u_64(deserializer);
    return BridgePlayerError(
      code: var_code,
      scene: var_scene,
      message: var_message,
      resource: var_resource,
      actual: var_actual,
      limit: var_limit,
    );
  }

  @protected
  BridgePlayerHistoryResult sse_decode_bridge_player_history_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_page = sse_decode_opt_box_autoadd_bridge_history_page(deserializer);
    var var_error = sse_decode_opt_box_autoadd_bridge_player_error(
      deserializer,
    );
    return BridgePlayerHistoryResult(page: var_page, error: var_error);
  }

  @protected
  BridgePlayerLimits sse_decode_bridge_player_limits(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_operationsPerInteraction = sse_decode_u_64(deserializer);
    var var_logicDepth = sse_decode_u_64(deserializer);
    var var_pendingEventsPerScene = sse_decode_u_64(deserializer);
    var var_arrayElements = sse_decode_u_64(deserializer);
    var var_renderedBytes = sse_decode_u_64(deserializer);
    var var_historyEntries = sse_decode_u_64(deserializer);
    var var_historyBytes = sse_decode_u_64(deserializer);
    var var_saveBytes = sse_decode_u_64(deserializer);
    return BridgePlayerLimits(
      operationsPerInteraction: var_operationsPerInteraction,
      logicDepth: var_logicDepth,
      pendingEventsPerScene: var_pendingEventsPerScene,
      arrayElements: var_arrayElements,
      renderedBytes: var_renderedBytes,
      historyEntries: var_historyEntries,
      historyBytes: var_historyBytes,
      saveBytes: var_saveBytes,
    );
  }

  @protected
  BridgePlayerSaveResult sse_decode_bridge_player_save_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bytes = sse_decode_opt_list_prim_u_8_strict(deserializer);
    var var_error = sse_decode_opt_box_autoadd_bridge_player_error(
      deserializer,
    );
    return BridgePlayerSaveResult(bytes: var_bytes, error: var_error);
  }

  @protected
  BridgeSemanticChoice sse_decode_bridge_semantic_choice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_targetScene = sse_decode_String(deserializer);
    return BridgeSemanticChoice(text: var_text, targetScene: var_targetScene);
  }

  @protected
  BridgeSemanticEvent sse_decode_bridge_semantic_event(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_scene = sse_decode_opt_String(deserializer);
    var var_actorId = sse_decode_opt_String(deserializer);
    var var_actorName = sse_decode_opt_String(deserializer);
    var var_emotion = sse_decode_opt_String(deserializer);
    var var_position = sse_decode_opt_String(deserializer);
    var var_portraitPath = sse_decode_opt_String(deserializer);
    var var_choices = sse_decode_list_bridge_semantic_choice(deserializer);
    var var_error = sse_decode_opt_box_autoadd_bridge_player_error(
      deserializer,
    );
    return BridgeSemanticEvent(
      kind: var_kind,
      text: var_text,
      scene: var_scene,
      actorId: var_actorId,
      actorName: var_actorName,
      emotion: var_emotion,
      position: var_position,
      portraitPath: var_portraitPath,
      choices: var_choices,
      error: var_error,
    );
  }

  @protected
  BridgeSourcePlayerOpenResult sse_decode_bridge_source_player_open_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_opened =
        sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
          deserializer,
        );
    var var_error = sse_decode_opt_box_autoadd_bridge_player_error(
      deserializer,
    );
    return BridgeSourcePlayerOpenResult(opened: var_opened, error: var_error);
  }

  @protected
  BridgeState sse_decode_bridge_state(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_u_64(deserializer);
    var var_scriptName = sse_decode_String(deserializer);
    var var_scene = sse_decode_String(deserializer);
    var var_bg = sse_decode_opt_String(deserializer);
    var var_bgm = sse_decode_opt_String(deserializer);
    var var_finished = sse_decode_bool(deserializer);
    var var_variables = sse_decode_list_bridge_variable(deserializer);
    var var_current = sse_decode_opt_box_autoadd_bridge_step(deserializer);
    var var_history = sse_decode_list_bridge_step(deserializer);
    return BridgeState(
      sessionId: var_sessionId,
      scriptName: var_scriptName,
      scene: var_scene,
      bg: var_bg,
      bgm: var_bgm,
      finished: var_finished,
      variables: var_variables,
      current: var_current,
      history: var_history,
    );
  }

  @protected
  BridgeStep sse_decode_bridge_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_text = sse_decode_opt_String(deserializer);
    var var_actorName = sse_decode_opt_String(deserializer);
    var var_actorId = sse_decode_opt_String(deserializer);
    var var_emotion = sse_decode_opt_String(deserializer);
    var var_position = sse_decode_opt_String(deserializer);
    var var_choices = sse_decode_list_bridge_choice(deserializer);
    return BridgeStep(
      kind: var_kind,
      text: var_text,
      actorName: var_actorName,
      actorId: var_actorId,
      emotion: var_emotion,
      position: var_position,
      choices: var_choices,
    );
  }

  @protected
  BridgeVariable sse_decode_bridge_variable(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return BridgeVariable(name: var_name, value: var_value);
  }

  @protected
  List<BridgeChoice> sse_decode_list_bridge_choice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeChoice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_choice(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeHistoryEntry> sse_decode_list_bridge_history_entry(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeMediaEffect> sse_decode_list_bridge_media_effect(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeMediaEffect>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_media_effect(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeSemanticChoice> sse_decode_list_bridge_semantic_choice(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeSemanticChoice>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_semantic_choice(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeStep> sse_decode_list_bridge_step(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeStep>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_step(deserializer));
    }
    return ans_;
  }

  @protected
  List<BridgeVariable> sse_decode_list_bridge_variable(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BridgeVariable>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_bridge_variable(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeSourcePlayerOpened?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
        deserializer,
      ));
    } else {
      return null;
    }
  }

  @protected
  BridgeHistoryPage? sse_decode_opt_box_autoadd_bridge_history_page(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_history_page(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgePlayerDelta? sse_decode_opt_box_autoadd_bridge_player_delta(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_player_delta(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgePlayerError? sse_decode_opt_box_autoadd_bridge_player_error(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_player_error(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BridgeStep? sse_decode_opt_box_autoadd_bridge_step(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_bridge_step(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeSourcePlayerOpenedImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SourcePlayerResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SourcePlayerResourceImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeSourcePlayerOpenedImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeSourcePlayerOpenedImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SourcePlayerResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SourcePlayerResourceImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as BridgeSourcePlayerOpenedImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SourcePlayerResource self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as SourcePlayerResourceImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
      self,
      serializer,
    );
  }

  @protected
  void sse_encode_box_autoadd_bridge_history_page(
    BridgeHistoryPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_history_page(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_player_delta(
    BridgePlayerDelta self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_player_delta(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_player_error(
    BridgePlayerError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_player_error(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_player_limits(
    BridgePlayerLimits self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_player_limits(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_bridge_step(
    BridgeStep self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_step(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_bridge_choice(BridgeChoice self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.target, serializer);
  }

  @protected
  void sse_encode_bridge_history_entry(
    BridgeHistoryEntry self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sequence, serializer);
    sse_encode_bridge_semantic_event(self.event, serializer);
    sse_encode_list_bridge_media_effect(self.effects, serializer);
    sse_encode_String(self.scene, serializer);
  }

  @protected
  void sse_encode_bridge_history_page(
    BridgeHistoryPage self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_bridge_history_entry(self.entries, serializer);
    sse_encode_u_64(self.nextSequence, serializer);
    sse_encode_u_64(self.firstRetainedSequence, serializer);
    sse_encode_u_64(self.omittedHistoryCount, serializer);
  }

  @protected
  void sse_encode_bridge_media_effect(
    BridgeMediaEffect self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.path, serializer);
  }

  @protected
  void sse_encode_bridge_player_action_result(
    BridgePlayerActionResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_bridge_player_delta(self.delta, serializer);
    sse_encode_opt_box_autoadd_bridge_player_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_player_delta(
    BridgePlayerDelta self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bridge_semantic_event(self.event, serializer);
    sse_encode_list_bridge_media_effect(self.effects, serializer);
    sse_encode_String(self.scene, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_u_64(self.sequence, serializer);
    sse_encode_u_64(self.firstRetainedSequence, serializer);
    sse_encode_u_64(self.omittedHistoryCount, serializer);
  }

  @protected
  void sse_encode_bridge_player_dispose_result(
    BridgePlayerDisposeResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.released, serializer);
    sse_encode_opt_box_autoadd_bridge_player_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_player_error(
    BridgePlayerError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.scene, serializer);
    sse_encode_String(self.message, serializer);
    sse_encode_opt_String(self.resource, serializer);
    sse_encode_opt_box_autoadd_u_64(self.actual, serializer);
    sse_encode_opt_box_autoadd_u_64(self.limit, serializer);
  }

  @protected
  void sse_encode_bridge_player_history_result(
    BridgePlayerHistoryResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_bridge_history_page(self.page, serializer);
    sse_encode_opt_box_autoadd_bridge_player_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_player_limits(
    BridgePlayerLimits self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.operationsPerInteraction, serializer);
    sse_encode_u_64(self.logicDepth, serializer);
    sse_encode_u_64(self.pendingEventsPerScene, serializer);
    sse_encode_u_64(self.arrayElements, serializer);
    sse_encode_u_64(self.renderedBytes, serializer);
    sse_encode_u_64(self.historyEntries, serializer);
    sse_encode_u_64(self.historyBytes, serializer);
    sse_encode_u_64(self.saveBytes, serializer);
  }

  @protected
  void sse_encode_bridge_player_save_result(
    BridgePlayerSaveResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_list_prim_u_8_strict(self.bytes, serializer);
    sse_encode_opt_box_autoadd_bridge_player_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_semantic_choice(
    BridgeSemanticChoice self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.targetScene, serializer);
  }

  @protected
  void sse_encode_bridge_semantic_event(
    BridgeSemanticEvent self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.scene, serializer);
    sse_encode_opt_String(self.actorId, serializer);
    sse_encode_opt_String(self.actorName, serializer);
    sse_encode_opt_String(self.emotion, serializer);
    sse_encode_opt_String(self.position, serializer);
    sse_encode_opt_String(self.portraitPath, serializer);
    sse_encode_list_bridge_semantic_choice(self.choices, serializer);
    sse_encode_opt_box_autoadd_bridge_player_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_source_player_open_result(
    BridgeSourcePlayerOpenResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
      self.opened,
      serializer,
    );
    sse_encode_opt_box_autoadd_bridge_player_error(self.error, serializer);
  }

  @protected
  void sse_encode_bridge_state(BridgeState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.sessionId, serializer);
    sse_encode_String(self.scriptName, serializer);
    sse_encode_String(self.scene, serializer);
    sse_encode_opt_String(self.bg, serializer);
    sse_encode_opt_String(self.bgm, serializer);
    sse_encode_bool(self.finished, serializer);
    sse_encode_list_bridge_variable(self.variables, serializer);
    sse_encode_opt_box_autoadd_bridge_step(self.current, serializer);
    sse_encode_list_bridge_step(self.history, serializer);
  }

  @protected
  void sse_encode_bridge_step(BridgeStep self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.text, serializer);
    sse_encode_opt_String(self.actorName, serializer);
    sse_encode_opt_String(self.actorId, serializer);
    sse_encode_opt_String(self.emotion, serializer);
    sse_encode_opt_String(self.position, serializer);
    sse_encode_list_bridge_choice(self.choices, serializer);
  }

  @protected
  void sse_encode_bridge_variable(
    BridgeVariable self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_list_bridge_choice(
    List<BridgeChoice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_choice(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_history_entry(
    List<BridgeHistoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_media_effect(
    List<BridgeMediaEffect> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_media_effect(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_semantic_choice(
    List<BridgeSemanticChoice> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_semantic_choice(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_step(
    List<BridgeStep> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_step(item, serializer);
    }
  }

  @protected
  void sse_encode_list_bridge_variable(
    List<BridgeVariable> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_bridge_variable(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
        self,
        serializer,
      );
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_history_page(
    BridgeHistoryPage? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_history_page(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_player_delta(
    BridgePlayerDelta? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_player_delta(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_player_error(
    BridgePlayerError? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_player_error(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_bridge_step(
    BridgeStep? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_bridge_step(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class BridgeSourcePlayerOpenedImpl extends RustOpaque
    implements BridgeSourcePlayerOpened {
  // Not to be used by end users
  BridgeSourcePlayerOpenedImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  BridgeSourcePlayerOpenedImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_BridgeSourcePlayerOpened,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_BridgeSourcePlayerOpened,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_BridgeSourcePlayerOpenedPtr,
  );

  BridgePlayerDelta get current => RustLib.instance.api
      .crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetCurrent(
        that: this,
      );

  SourcePlayerResource get resource => RustLib.instance.api
      .crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorGetResource(
        that: this,
      );

  set current(BridgePlayerDelta current) => RustLib.instance.api
      .crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetCurrent(
        that: this,
        current: current,
      );

  set resource(SourcePlayerResource resource) => RustLib.instance.api
      .crateApiPlayerV2BridgeSourcePlayerOpenedAutoAccessorSetResource(
        that: this,
        resource: resource,
      );
}

@sealed
class SourcePlayerResourceImpl extends RustOpaque
    implements SourcePlayerResource {
  // Not to be used by end users
  SourcePlayerResourceImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  SourcePlayerResourceImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_increment_strong_count_SourcePlayerResource,
    rustArcDecrementStrongCount: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SourcePlayerResource,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_SourcePlayerResourcePtr,
  );
}
