// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/player.dart';
import 'api/player_v2.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_BridgeSourcePlayerOpenedPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpenedPtr;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_SourcePlayerResourcePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResourcePtr;

  @protected
  BridgeSourcePlayerOpened
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  );

  @protected
  SourcePlayerResource
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    dynamic raw,
  );

  @protected
  BridgeSourcePlayerOpened
  dco_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeSourcePlayerOpened
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  );

  @protected
  SourcePlayerResource
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    dynamic raw,
  );

  @protected
  BridgeSourcePlayerOpened
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  );

  @protected
  SourcePlayerResource
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  BridgeSourcePlayerOpened
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeHistoryPage dco_decode_box_autoadd_bridge_history_page(dynamic raw);

  @protected
  BridgePlayerDelta dco_decode_box_autoadd_bridge_player_delta(dynamic raw);

  @protected
  BridgePlayerError dco_decode_box_autoadd_bridge_player_error(dynamic raw);

  @protected
  BridgePlayerLimits dco_decode_box_autoadd_bridge_player_limits(dynamic raw);

  @protected
  BridgeStep dco_decode_box_autoadd_bridge_step(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BridgeChoice dco_decode_bridge_choice(dynamic raw);

  @protected
  BridgeHistoryEntry dco_decode_bridge_history_entry(dynamic raw);

  @protected
  BridgeHistoryPage dco_decode_bridge_history_page(dynamic raw);

  @protected
  BridgeMediaEffect dco_decode_bridge_media_effect(dynamic raw);

  @protected
  BridgePlayerActionResult dco_decode_bridge_player_action_result(dynamic raw);

  @protected
  BridgePlayerDelta dco_decode_bridge_player_delta(dynamic raw);

  @protected
  BridgePlayerDisposeResult dco_decode_bridge_player_dispose_result(
    dynamic raw,
  );

  @protected
  BridgePlayerError dco_decode_bridge_player_error(dynamic raw);

  @protected
  BridgePlayerHistoryResult dco_decode_bridge_player_history_result(
    dynamic raw,
  );

  @protected
  BridgePlayerLimits dco_decode_bridge_player_limits(dynamic raw);

  @protected
  BridgePlayerSaveResult dco_decode_bridge_player_save_result(dynamic raw);

  @protected
  BridgeSemanticChoice dco_decode_bridge_semantic_choice(dynamic raw);

  @protected
  BridgeSemanticEvent dco_decode_bridge_semantic_event(dynamic raw);

  @protected
  BridgeSourcePlayerOpenResult dco_decode_bridge_source_player_open_result(
    dynamic raw,
  );

  @protected
  BridgeState dco_decode_bridge_state(dynamic raw);

  @protected
  BridgeStep dco_decode_bridge_step(dynamic raw);

  @protected
  BridgeVariable dco_decode_bridge_variable(dynamic raw);

  @protected
  List<BridgeChoice> dco_decode_list_bridge_choice(dynamic raw);

  @protected
  List<BridgeHistoryEntry> dco_decode_list_bridge_history_entry(dynamic raw);

  @protected
  List<BridgeMediaEffect> dco_decode_list_bridge_media_effect(dynamic raw);

  @protected
  List<BridgeSemanticChoice> dco_decode_list_bridge_semantic_choice(
    dynamic raw,
  );

  @protected
  List<BridgeStep> dco_decode_list_bridge_step(dynamic raw);

  @protected
  List<BridgeVariable> dco_decode_list_bridge_variable(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BridgeSourcePlayerOpened?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    dynamic raw,
  );

  @protected
  BridgeHistoryPage? dco_decode_opt_box_autoadd_bridge_history_page(
    dynamic raw,
  );

  @protected
  BridgePlayerDelta? dco_decode_opt_box_autoadd_bridge_player_delta(
    dynamic raw,
  );

  @protected
  BridgePlayerError? dco_decode_opt_box_autoadd_bridge_player_error(
    dynamic raw,
  );

  @protected
  BridgeStep? dco_decode_opt_box_autoadd_bridge_step(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  BridgeSourcePlayerOpened
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  SourcePlayerResource
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSourcePlayerOpened
  sse_decode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSourcePlayerOpened
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  SourcePlayerResource
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSourcePlayerOpened
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  SourcePlayerResource
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  BridgeSourcePlayerOpened
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryPage sse_decode_box_autoadd_bridge_history_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDelta sse_decode_box_autoadd_bridge_player_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerError sse_decode_box_autoadd_bridge_player_error(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerLimits sse_decode_box_autoadd_bridge_player_limits(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStep sse_decode_box_autoadd_bridge_step(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BridgeChoice sse_decode_bridge_choice(SseDeserializer deserializer);

  @protected
  BridgeHistoryEntry sse_decode_bridge_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryPage sse_decode_bridge_history_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgeMediaEffect sse_decode_bridge_media_effect(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerActionResult sse_decode_bridge_player_action_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDelta sse_decode_bridge_player_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDisposeResult sse_decode_bridge_player_dispose_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerError sse_decode_bridge_player_error(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerHistoryResult sse_decode_bridge_player_history_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerLimits sse_decode_bridge_player_limits(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerSaveResult sse_decode_bridge_player_save_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSemanticChoice sse_decode_bridge_semantic_choice(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSemanticEvent sse_decode_bridge_semantic_event(
    SseDeserializer deserializer,
  );

  @protected
  BridgeSourcePlayerOpenResult sse_decode_bridge_source_player_open_result(
    SseDeserializer deserializer,
  );

  @protected
  BridgeState sse_decode_bridge_state(SseDeserializer deserializer);

  @protected
  BridgeStep sse_decode_bridge_step(SseDeserializer deserializer);

  @protected
  BridgeVariable sse_decode_bridge_variable(SseDeserializer deserializer);

  @protected
  List<BridgeChoice> sse_decode_list_bridge_choice(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeHistoryEntry> sse_decode_list_bridge_history_entry(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeMediaEffect> sse_decode_list_bridge_media_effect(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeSemanticChoice> sse_decode_list_bridge_semantic_choice(
    SseDeserializer deserializer,
  );

  @protected
  List<BridgeStep> sse_decode_list_bridge_step(SseDeserializer deserializer);

  @protected
  List<BridgeVariable> sse_decode_list_bridge_variable(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BridgeSourcePlayerOpened?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    SseDeserializer deserializer,
  );

  @protected
  BridgeHistoryPage? sse_decode_opt_box_autoadd_bridge_history_page(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerDelta? sse_decode_opt_box_autoadd_bridge_player_delta(
    SseDeserializer deserializer,
  );

  @protected
  BridgePlayerError? sse_decode_opt_box_autoadd_bridge_player_error(
    SseDeserializer deserializer,
  );

  @protected
  BridgeStep? sse_decode_opt_box_autoadd_bridge_step(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SourcePlayerResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_RefMut_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SourcePlayerResource self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    SourcePlayerResource self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_history_page(
    BridgeHistoryPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_player_delta(
    BridgePlayerDelta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_player_error(
    BridgePlayerError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_player_limits(
    BridgePlayerLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_bridge_step(
    BridgeStep self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_choice(BridgeChoice self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_history_entry(
    BridgeHistoryEntry self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_history_page(
    BridgeHistoryPage self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_media_effect(
    BridgeMediaEffect self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_action_result(
    BridgePlayerActionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_delta(
    BridgePlayerDelta self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_dispose_result(
    BridgePlayerDisposeResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_error(
    BridgePlayerError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_history_result(
    BridgePlayerHistoryResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_limits(
    BridgePlayerLimits self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_player_save_result(
    BridgePlayerSaveResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_semantic_choice(
    BridgeSemanticChoice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_semantic_event(
    BridgeSemanticEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_source_player_open_result(
    BridgeSourcePlayerOpenResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bridge_state(BridgeState self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_step(BridgeStep self, SseSerializer serializer);

  @protected
  void sse_encode_bridge_variable(
    BridgeVariable self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_choice(
    List<BridgeChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_history_entry(
    List<BridgeHistoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_media_effect(
    List<BridgeMediaEffect> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_semantic_choice(
    List<BridgeSemanticChoice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_step(
    List<BridgeStep> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_bridge_variable(
    List<BridgeVariable> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    BridgeSourcePlayerOpened? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_history_page(
    BridgeHistoryPage? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_player_delta(
    BridgePlayerDelta? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_player_error(
    BridgePlayerError? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_bridge_step(
    BridgeStep? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpenedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_storyscript_player_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpenedPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpenedPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_storyscript_player_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpened =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerBridgeSourcePlayerOpenedPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResourcePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_storyscript_player_core_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResourcePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResourcePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_storyscript_player_core_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResource =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerSourcePlayerResourcePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
